In [8]:
from transformers import pipeline

In [9]:
ppl = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [22]:
ppl("I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered 'controversial' I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it's not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn't have much of a plot.")

[{'label': 'POSITIVE', 'score': 0.785426139831543}]

In [26]:
ppl("'I Am Curious:' Yellow is a risible and pretentious steaming pile. It doesn't matter what one's political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn't true. I've seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don't exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we're treated to the site of Vincent Gallo's throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) 'double-standard' in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, and the same cannot be said for a man. In fact, you generally won't see female genitals in an American film in anything short of porn or explicit erotica. This alleged double-standard is less a double standard than an admittedly depressing ability to come to terms culturally with the insides of women's bodies.")

[{'label': 'NEGATIVE', 'score': 0.9990228414535522}]

In [27]:
ppl("If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives (unless one comes up with one while one's mind wanders, as it will invariably do during this pointless film).<br /><br />One might better spend one's time staring out a window at a tree growing.<br /><br />")

[{'label': 'NEGATIVE', 'score': 0.998217761516571}]

In [28]:
ppl("I love sci-fi and am willing to put up with a lot. Sci-fi movies/TV are usually underfunded, under-appreciated and misunderstood. I tried to like this, I really did, but it is to good TV sci-fi as Babylon 5 is to Star Trek (the original). Silly prosthetics, cheap cardboard sets, stilted dialogues, CG that doesn't match the background, and painfully one-dimensional characters cannot be overcome with a 'sci-fi' setting. (I'm sure there are those of you out there who think Babylon 5 is good sci-fi TV. It's not. It's clichéd and uninspiring.) While US viewers might like emotion and character development, sci-fi is a genre that does not take itself seriously (cf. Star Trek). It may treat important issues, yet not as a serious philosophy. It's really difficult to care about the characters here as they are not simply foolish, just missing a spark of life. Their actions and reactions are wooden and predictable, often painful to watch. The makers of Earth KNOW it's rubbish as they have to always say 'Gene Roddenberry's Earth...' otherwise people would not continue watching. Roddenberry's ashes must be turning in their orbit as this dull, cheap, poorly edited (watching it without advert breaks really brings this home) trudging Trabant of a show lumbers into space. Spoiler. So, kill off a main character. And then bring him back as another actor. Jeeez! Dallas all over again.")

[{'label': 'NEGATIVE', 'score': 0.9996143579483032}]

In [29]:
ppl("The Forgotten (AKA: Don't Look In The Basement) is a very cheaply made and very old looking horror movie.<br /><br />The story is very slow and never really reaches anything worth getting excited about.<br /><br />The patients at the asylum are embarrassingly funny especially Sam and the old woman who always quotes an old saying to everyone. (Look out for the bit when she gets close to the camera, tell me you can watch without laughing!).<br /><br />Now the gore is very poor looking, with the blood looking pink in many scenes so it doesn't really deserve its place on the video nasties list!.<br /><br />Overall if you aren't looking for a fantastic horror film and have some time to spare then it's worth a watch.")

[{'label': 'NEGATIVE', 'score': 0.9971417784690857}]

In [30]:
ppl("I was looking forward to this movie. Trustworthy actors, interesting plot. Great atmosphere then ????? IF you are going to attempt something that is meant to encapsulate the meaning of life. First. Know it. OK I did not expect the directors or writers to actually know the meaning but I thought they may have offered crumbs to peck at and treats to add fuel to the fire-Which! they almost did. Things I didn't get. A woman wandering around in dark places and lonely car parks alone-oblivious to the consequences. Great riddles that fell by the wayside. The promise of the knowledge therein contained by the original so-called criminal. I had no problem with the budget and enjoyed the suspense. I understood and can wax lyrical about the fool and found Adrian Pauls role crucial and penetrating and then ????? Basically the story line and the script where good up to a point and that point was the last 10 minutes or so. What? Run out of ideas! Such a pity that this movie had to let us down so badly. It may not comprehend the meaning and I really did not expect the writers to understand it but I was hoping for an intellectual, if not spiritual ride and got a bump in the road")

[{'label': 'NEGATIVE', 'score': 0.9808396100997925}]

In [33]:
ppl("It's Saturday, it's raining, and I think every movie should have at least one comment... so I just watched 'The Crime Doctor's Courage' all the way through. It's a murder mystery with a typical cast of characters, and a couple of the usual suspects -- each with their own possible motive for the crime. The story starts abruptly and the viewer is thrown into the plot with no character development or storytelling whatsoever. I guess that's not too surprising for a B movie of this period. There are also some moments which look and feel like this is pre-WWII, but perhaps that is due to the writer's background in radio shows.<br /><br />The 'Crime Doctor' is the sleuth who happens to be visiting California for some R&R from his psychiatry practice on the East coast. He hooks up with a mystery novelist friend with whom it is implied has been along for one or more previous mystery solving capers. The novelist occasionally fills the role of sidekick to our sleuth (AKA Dr. Watson), and also occasionally lightens things up with a bit of comic relief (sort of).<br /><br />There is also a somewhat simple, but not quite bumbling police captain who at times is annoyed by the meddling sleuth. And then there are the mysterious Braggas, a brother and sister who are dance artists at a night-club. The dance is sort of an interpretive dance that happens to be one of those moments which feels more like the 30's than the 40's. Though the story location is California, the Braggas appear to live in a castle!<br /><br />There was one plot element which managed to keep me somewhat amused, but I won't divulge any more than that because I always enjoy movies more when the story is discovered, rather than known in advance. (even though I can think of many, many, B films which would rate higher and it is difficult to say that watching this one is time well spent) I have not seen any other movies from the 'Crime Doctor' series, so I can't make any comparisons.")

[{'label': 'NEGATIVE', 'score': 0.9950559139251709}]

In [34]:
ppl("My birthday is coming June 3.")

[{'label': 'POSITIVE', 'score': 0.9980406165122986}]

In [1]:
import datasets
from datasets import load_dataset

In [3]:
dataset = load_dataset("bdstar/twitter-sentiment-analysis")

README.md: 0.00B [00:00, ?B/s]

train.json:   0%|          | 0.00/361M [00:00<?, ?B/s]

validation.json: 0.00B [00:00, ?B/s]

test.json:   0%|          | 0.00/198M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3142209 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/31014 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1600000 [00:00<?, ? examples/s]

In [6]:
dataset["test"][0]

{'ID': 1,
 'text': "@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D",
 'label': 'negative'}

In [14]:
from transformers.pipelines.pt_utils import KeyDataset
from tqdm import tqdm

labels = []
cnt = 0
for output in tqdm(ppl(KeyDataset(dataset["test"], "text"))):
    labels.append(output)
    cnt += 1
    if cnt > 15000:
        break

  1%|          | 15000/1600000 [01:23<2:27:22, 179.25it/s]

In [17]:
true_labels = [elem["label"] for elem in dataset["test"]]

In [18]:
true_labels_ = true_labels[:15000]

In [20]:
true_labels_[0]

'negative'

In [24]:
idxs_scores = []
for i, elem in enumerate(list(zip(true_labels_, labels))):
    if elem[1]["label"].lower() != elem[0]:
        idxs_scores.append((i, elem[1]['score']))

In [25]:
idxs_scores

[(2, 0.9374226331710815),
 (3, 0.9769710898399353),
 (7, 0.9988188147544861),
 (10, 0.9863536357879639),
 (13, 0.9836906790733337),
 (15, 0.9960423707962036),
 (18, 0.9958595633506775),
 (24, 0.8788506984710693),
 (28, 0.9855452179908752),
 (33, 0.9995993971824646),
 (54, 0.969510018825531),
 (59, 0.9986541271209717),
 (62, 0.9718125462532043),
 (64, 0.6713087558746338),
 (68, 0.9915140271186829),
 (71, 0.999025821685791),
 (72, 0.9951667785644531),
 (98, 0.7967628836631775),
 (99, 0.9564703106880188),
 (102, 0.9814617037773132),
 (104, 0.9913710355758667),
 (109, 0.9544031620025635),
 (114, 0.9879265427589417),
 (115, 0.9981805086135864),
 (116, 0.9632769823074341),
 (122, 0.9975715279579163),
 (130, 0.9988922476768494),
 (142, 0.9938163757324219),
 (166, 0.9997403025627136),
 (168, 0.9875966906547546),
 (171, 0.9711063504219055),
 (182, 0.9611266851425171),
 (188, 0.9994162321090698),
 (196, 0.7068467736244202),
 (197, 0.9992142915725708),
 (204, 0.9164865612983704),
 (207, 0.99687260389328),
 (208, 0.7477068901062012),
 (222, 0.9997933506965637),
 (228, 0.9580824971199036),
 (229, 0.9708998799324036),
 (235, 0.9946160912513733),
 (237, 0.5508347153663635),
 (240, 0.9919652938842773),
 (243, 0.9894860982894897),
 (249, 0.7477068901062012),
 (257, 0.969253420829773),
 (262, 0.6084727048873901),
 (265, 0.9474431872367859),
 (275, 0.9958192110061646),
 (288, 0.9423415064811707),
 (290, 0.9997754693031311),
 (293, 0.9998525381088257),
 (296, 0.8104802966117859),
 (306, 0.9996463060379028),
 (314, 0.64616459608078),
 (324, 0.9994605183601379),
 (355, 0.9995647072792053),
 (358, 0.5578396320343018),
 (360, 0.9875307083129883),
 (361, 0.8489174246788025),
 (366, 0.7071743011474609),
 (385, 0.9154161214828491),
 (392, 0.9779698848724365),
 (393, 0.9982460737228394),
 (397, 0.8358812928199768),
 (402, 0.948229193687439),
 (407, 0.9461590051651001),
 (411, 0.9976255297660828),
 (429, 0.9433451294898987),
 (430, 0.9795380234718323),
 (431, 0.9934583306312561),
 (432, 0.8581237196922302),
 (437, 0.9404393434524536),
 (439, 0.9841966032981873),
 (450, 0.9913482069969177),
 (456, 0.9936793446540833),
 (468, 0.8236414790153503),
 (471, 0.9965498447418213),
 (475, 0.9962665438652039),
 (478, 0.9995189905166626),
 (483, 0.9046246409416199),
 (492, 0.9976786971092224),
 (496, 0.8972777724266052),
 (497, 0.9869592785835266),
 (502, 0.7543013691902161),
 (503, 0.9963628649711609),
 (508, 0.9701994061470032),
 (530, 0.9970932006835938),
 (544, 0.9995121955871582),
 (545, 0.9920561909675598),
 (549, 0.9982060194015503),
 (554, 0.9647505283355713),
 (559, 0.9947807192802429),
 (564, 0.9879882335662842),
 (567, 0.9218799471855164),
 (594, 0.9160952568054199),
 (615, 0.9839711785316467),
 (618, 0.9993278980255127),
 (624, 0.9996799230575562),
 (634, 0.9795947670936584),
 (643, 0.9890925884246826),
 (647, 0.9993172883987427),
 (648, 0.9996008276939392),
 (656, 0.9995911717414856),
 (663, 0.5908613204956055),
 (664, 0.9960663914680481),
 (665, 0.9978765249252319),
 (671, 0.9697590470314026),
 (683, 0.9920086860656738),
 (696, 0.9933159947395325),
 (697, 0.6925551891326904),
 (702, 0.9962475895881653),
 (709, 0.9538050889968872),
 (717, 0.9965014457702637),
 (719, 0.8262351155281067),
 (729, 0.6980178356170654),
 (731, 0.7412831783294678),
 (734, 0.9974790215492249),
 (736, 0.9102117419242859),
 (741, 0.9955022931098938),
 (750, 0.8068704605102539),
 (760, 0.9951293468475342),
 (766, 0.9948973059654236),
 (774, 0.9874626994132996),
 (779, 0.9945408701896667),
 (780, 0.865763783454895),
 (782, 0.9809979796409607),
 (784, 0.9784138202667236),
 (785, 0.9825703501701355),
 (796, 0.9992266893386841),
 (804, 0.9932776093482971),
 (824, 0.7704892158508301),
 (828, 0.9947360157966614),
 (829, 0.9773877263069153),
 (832, 0.9830418825149536),
 (838, 0.9840588569641113),
 (842, 0.9990990161895752),
 (847, 0.9912517666816711),
 (862, 0.8544611930847168),
 (869, 0.9994028806686401),
 (870, 0.9978421926498413),
 (878, 0.700172483921051),
 (881, 0.9455642104148865),
 (886, 0.9992510676383972),
 (890, 0.998704195022583),
 (901, 0.9995964169502258),
 (902, 0.9952322840690613),
 (904, 0.985590398311615),
 (909, 0.9777405261993408),
 (932, 0.9930251836776733),
 (940, 0.9970718622207642),
 (943, 0.9975009560585022),
 (949, 0.8407828211784363),
 (952, 0.9976811408996582),
 (961, 0.9566724300384521),
 (969, 0.998488187789917),
 (974, 0.9650530815124512),
 (977, 0.9989275336265564),
 (990, 0.9507676959037781),
 (992, 0.852418065071106),
 (995, 0.9959944486618042),
 (996, 0.9994345307350159),
 (997, 0.9961901903152466),
 (998, 0.9986492991447449),
 (1007, 0.9940283298492432),
 (1011, 0.6265650987625122),
 (1012, 0.6214264035224915),
 (1014, 0.8890195488929749),
 (1015, 0.9974391460418701),
 (1021, 0.9970110654830933),
 (1026, 0.9950992465019226),
 (1031, 0.8433318734169006),
 (1042, 0.9993911981582642),
 (1054, 0.9993908405303955),
 (1056, 0.9764986634254456),
 (1067, 0.9997259974479675),
 (1073, 0.9956907629966736),
 (1091, 0.995276689529419),
 (1093, 0.9790695309638977),
 (1095, 0.600983202457428),
 (1096, 0.6015600562095642),
 (1111, 0.9869149327278137),
 (1113, 0.9801650047302246),
 (1116, 0.9952677488327026),
 (1117, 0.9932329654693604),
 (1120, 0.9938344955444336),
 (1123, 0.9991320967674255),
 (1128, 0.9889783263206482),
 (1137, 0.9982119798660278),
 (1149, 0.998069703578949),
 (1155, 0.9978260397911072),
 (1170, 0.9949565529823303),
 (1172, 0.9937803149223328),
 (1174, 0.9670540690422058),
 (1177, 0.9204835891723633),
 (1182, 0.9997729659080505),
 (1187, 0.9987773299217224),
 (1193, 0.9996650218963623),
 (1200, 0.9981538653373718),
 (1203, 0.956465482711792),
 (1205, 0.986825168132782),
 (1206, 0.9905622601509094),
 (1210, 0.8627668619155884),
 (1212, 0.9867078065872192),
 (1230, 0.995240330696106),
 (1231, 0.9746014475822449),
 (1244, 0.9949764013290405),
 (1245, 0.997637152671814),
 (1250, 0.5858726501464844),
 (1254, 0.9995359182357788),
 (1256, 0.9998199343681335),
 (1258, 0.9885271787643433),
 (1264, 0.9982113838195801),
 (1265, 0.9994547963142395),
 (1283, 0.9976848363876343),
 (1284, 0.981145441532135),
 (1291, 0.9998133778572083),
 (1294, 0.878268837928772),
 (1296, 0.9578403830528259),
 (1298, 0.9998433589935303),
 (1300, 0.985744059085846),
 (1301, 0.9175845980644226),
 (1313, 0.9911836385726929),
 (1329, 0.9963709115982056),
 (1330, 0.9983433485031128),
 (1334, 0.9545092582702637),
 (1339, 0.5203704833984375),
 (1355, 0.9767166376113892),
 (1358, 0.9992782473564148),
 (1363, 0.9911476373672485),
 (1364, 0.9996955394744873),
 (1372, 0.6425584554672241),
 (1378, 0.8951324224472046),
 (1379, 0.9961714148521423),
 (1380, 0.9870784282684326),
 (1383, 0.999539852142334),
 (1396, 0.9880735278129578),
 (1411, 0.9993724226951599),
 (1418, 0.6447528004646301),
 (1425, 0.8078588843345642),
 (1428, 0.9973245859146118),
 (1438, 0.9749279022216797),
 (1454, 0.9881850481033325),
 (1464, 0.9970591068267822),
 (1471, 0.9414500594139099),
 (1473, 0.9206172227859497),
 (1484, 0.94952791929245),
 (1485, 0.5399767756462097),
 (1501, 0.8988137245178223),
 (1510, 0.9493922591209412),
 (1512, 0.5574489831924438),
 (1513, 0.9843782782554626),
 (1517, 0.7992644906044006),
 (1520, 0.9657695889472961),
 (1521, 0.995572566986084),
 (1522, 0.9770137667655945),
 (1523, 0.995119571685791),
 (1526, 0.9711999893188477),
 (1536, 0.9827643036842346),
 (1539, 0.9985779523849487),
 (1540, 0.9898660778999329),
 (1547, 0.9876438975334167),
 (1558, 0.9403154850006104),
 (1560, 0.997951328754425),
 (1562, 0.9945865869522095),
 (1563, 0.9526197910308838),
 (1566, 0.692281186580658),
 (1567, 0.8090732097625732),
 (1571, 0.9381821155548096),
 (1577, 0.999776303768158),
 (1582, 0.9990527033805847),
 (1585, 0.9833806753158569),
 (1589, 0.7794957756996155),
 (1595, 0.9990204572677612),
 (1596, 0.5725770592689514),
 (1606, 0.991561233997345),
 (1608, 0.9868054389953613),
 (1618, 0.9816449880599976),
 (1620, 0.9764873385429382),
 (1622, 0.9007568359375),
 (1625, 0.9982653260231018),
 (1639, 0.9995875954627991),
 (1642, 0.9448996186256409),
 (1652, 0.9931004047393799),
 (1661, 0.9195285439491272),
 (1664, 0.6524539589881897),
 (1669, 0.9884490370750427),
 (1673, 0.9534174203872681),
 (1679, 0.6489884257316589),
 (1680, 0.9976512789726257),
 (1681, 0.7321339845657349),
 (1697, 0.9932676553726196),
 (1701, 0.9659587740898132),
 (1706, 0.9972652196884155),
 (1711, 0.9831261038780212),
 (1713, 0.9141274690628052),
 (1715, 0.9355536103248596),
 (1729, 0.9696406722068787),
 (1731, 0.9128282070159912),
 (1732, 0.9946005344390869),
 (1733, 0.9576932787895203),
 (1738, 0.9348899126052856),
 (1740, 0.9957259893417358),
 (1741, 0.9996063113212585),
 (1744, 0.9011375308036804),
 (1748, 0.9993769526481628),
 (1756, 0.8727346062660217),
 (1758, 0.993830144405365),
 (1761, 0.982049286365509),
 (1774, 0.9997054934501648),
 (1777, 0.9989426732063293),
 (1791, 0.9897253513336182),
 (1797, 0.9859977960586548),
 (1821, 0.9981333613395691),
 (1827, 0.9685636758804321),
 (1830, 0.9994196891784668),
 (1834, 0.9248206615447998),
 (1841, 0.9793015718460083),
 (1842, 0.9997957348823547),
 (1843, 0.9912573099136353),
 (1844, 0.971920371055603),
 (1847, 0.9916717410087585),
 (1848, 0.9964851140975952),
 (1852, 0.9899817109107971),
 (1863, 0.8955062031745911),
 (1868, 0.9933253526687622),
 (1876, 0.5840368866920471),
 (1878, 0.9995730519294739),
 (1885, 0.9989141225814819),
 (1891, 0.9923134446144104),
 (1893, 0.9996451139450073),
 (1894, 0.9995757937431335),
 (1906, 0.9982082843780518),
 (1915, 0.9991833567619324),
 (1916, 0.9930781722068787),
 (1918, 0.807780385017395),
 (1920, 0.8775854706764221),
 (1930, 0.9616091251373291),
 (1931, 0.9982314705848694),
 (1935, 0.9775779247283936),
 (1936, 0.9992563128471375),
 (1940, 0.807780385017395),
 (1946, 0.9995970129966736),
 (1950, 0.9982670545578003),
 (1954, 0.9865021705627441),
 (1962, 0.9991088509559631),
 (1966, 0.8555082082748413),
 (1973, 0.9901216626167297),
 (1979, 0.9413350820541382),
 (1980, 0.7311100363731384),
 (1989, 0.8144141435623169),
 (1990, 0.9994593262672424),
 (1994, 0.9956786036491394),
 (1997, 0.857620894908905),
 (2003, 0.9984166622161865),
 (2004, 0.9942615032196045),
 (2006, 0.8142027258872986),
 (2008, 0.9861758351325989),
 (2028, 0.9988486766815186),
 (2030, 0.8548017144203186),
 (2043, 0.5492299199104309),
 (2047, 0.9996616840362549),
 (2059, 0.9544865489006042),
 (2061, 0.9931429624557495),
 (2064, 0.9978087544441223),
 (2067, 0.9934012293815613),
 (2068, 0.9977688789367676),
 (2070, 0.9992579817771912),
 (2071, 0.9886511564254761),
 (2080, 0.9961532950401306),
 (2083, 0.9779514074325562),
 (2086, 0.8800390362739563),
 (2091, 0.7160181999206543),
 (2094, 0.9461596608161926),
 (2095, 0.9981655478477478),
 (2097, 0.9932768940925598),
 (2106, 0.9114018082618713),
 (2108, 0.8014634251594543),
 (2112, 0.9907321333885193),
 (2121, 0.9966089725494385),
 (2133, 0.9783065915107727),
 (2138, 0.9987354874610901),
 (2140, 0.9964428544044495),
 (2141, 0.6151139736175537),
 (2142, 0.9928681254386902),
 (2158, 0.9933342933654785),
 (2168, 0.9743677973747253),
 (2170, 0.9935318231582642),
 (2178, 0.9886952042579651),
 (2179, 0.990728497505188),
 (2190, 0.9992202520370483),
 (2193, 0.9928320646286011),
 (2201, 0.8692992329597473),
 (2215, 0.9974942207336426),
 (2229, 0.9800089597702026),
 (2234, 0.9911175966262817),
 (2235, 0.836005687713623),
 (2237, 0.9990691542625427),
 (2246, 0.9944671392440796),
 (2247, 0.9891061186790466),
 (2264, 0.9970365762710571),
 (2268, 0.999815046787262),
 (2270, 0.998939573764801),
 (2287, 0.9861975312232971),
 (2297, 0.9986044764518738),
 (2298, 0.9969664216041565),
 (2310, 0.9995381832122803),
 (2319, 0.9818649291992188),
 (2334, 0.8366991877555847),
 (2336, 0.995870053768158),
 (2337, 0.9569777846336365),
 (2340, 0.9285786747932434),
 (2341, 0.9994837045669556),
 (2342, 0.9641053080558777),
 (2345, 0.9983944296836853),
 (2352, 0.9996688365936279),
 (2354, 0.9995618462562561),
 (2357, 0.614626407623291),
 (2367, 0.9878591895103455),
 (2390, 0.9913353323936462),
 (2393, 0.9984614849090576),
 (2396, 0.8645981550216675),
 (2409, 0.5067603588104248),
 (2412, 0.7025076150894165),
 (2423, 0.9953226447105408),
 (2424, 0.9988405108451843),
 (2428, 0.9989234805107117),
 (2429, 0.9846369028091431),
 (2439, 0.9990905523300171),
 (2440, 0.9670480489730835),
 (2443, 0.9981496334075928),
 (2445, 0.9822596311569214),
 (2452, 0.9945635199546814),
 (2454, 0.9996862411499023),
 (2460, 0.7612764239311218),
 (2461, 0.9937583208084106),
 (2462, 0.7153956890106201),
 (2469, 0.9964690208435059),
 (2471, 0.9919102787971497),
 (2480, 0.9992783665657043),
 (2483, 0.8254716396331787),
 (2489, 0.980048418045044),
 (2492, 0.9996021389961243),
 (2495, 0.9956738352775574),
 (2508, 0.7594743967056274),
 (2520, 0.9996738433837891),
 (2543, 0.9952580332756042),
 (2544, 0.9847890138626099),
 (2568, 0.9788307547569275),
 (2569, 0.9967453479766846),
 (2573, 0.9993866682052612),
 (2575, 0.9996053576469421),
 (2576, 0.900017261505127),
 (2580, 0.9792580008506775),
 (2585, 0.9902618527412415),
 (2587, 0.9892271757125854),
 (2589, 0.9862216711044312),
 (2597, 0.9864904880523682),
 (2604, 0.9943631887435913),
 (2612, 0.999603807926178),
 (2616, 0.9401463270187378),
 (2618, 0.9452361464500427),
 (2619, 0.9967958331108093),
 (2621, 0.9940781593322754),
 (2635, 0.9993226528167725),
 (2640, 0.6774970889091492),
 (2642, 0.9987980127334595),
 (2648, 0.5623149871826172),
 (2649, 0.6215498447418213),
 (2660, 0.979151725769043),
 (2662, 0.9961299896240234),
 (2669, 0.9997691512107849),
 (2675, 0.9786549210548401),
 (2681, 0.5582654476165771),
 (2686, 0.9997150301933289),
 (2688, 0.9791279435157776),
 (2690, 0.9989075660705566),
 (2703, 0.999049961566925),
 (2705, 0.998915433883667),
 (2708, 0.9591931104660034),
 (2717, 0.9883272051811218),
 (2727, 0.9946282505989075),
 (2733, 0.9904897212982178),
 (2744, 0.9997972846031189),
 (2746, 0.9992734789848328),
 (2747, 0.9835107326507568),
 (2748, 0.9950408339500427),
 (2751, 0.9404758214950562),
 (2754, 0.9327314496040344),
 (2756, 0.9991719722747803),
 (2757, 0.9990482926368713),
 (2760, 0.9979456067085266),
 (2761, 0.9921820163726807),
 (2764, 0.9980114698410034),
 (2765, 0.9093531370162964),
 (2771, 0.9196880459785461),
 (2773, 0.9391477108001709),
 (2778, 0.6229337453842163),
 (2786, 0.9785234928131104),
 (2787, 0.9872540831565857),
 (2792, 0.9463440775871277),
 (2794, 0.9994282126426697),
 (2797, 0.9980280995368958),
 (2804, 0.7829352617263794),
 (2816, 0.9688735604286194),
 (2821, 0.9997267127037048),
 (2829, 0.9968675971031189),
 (2834, 0.6875566840171814),
 (2845, 0.8688328266143799),
 (2853, 0.9971557855606079),
 (2854, 0.9762114882469177),
 (2860, 0.9998334646224976),
 (2864, 0.9995218515396118),
 (2879, 0.9831394553184509),
 (2880, 0.8991750478744507),
 (2881, 0.999211311340332),
 (2885, 0.9868450164794922),
 (2899, 0.6550227999687195),
 (2906, 0.9981269240379333),
 (2908, 0.901075005531311),
 (2909, 0.9281590580940247),
 (2912, 0.9876676201820374),
 (2921, 0.9302642941474915),
 (2924, 0.988247811794281),
 (2927, 0.9846973419189453),
 (2930, 0.9997896552085876),
 (2954, 0.9998413324356079),
 (2955, 0.8355330228805542),
 (2959, 0.9993459582328796),
 (2961, 0.9777787327766418),
 (2962, 0.9969372749328613),
 (2981, 0.9959675073623657),
 (2984, 0.9967941641807556),
 (2986, 0.9743623733520508),
 (2990, 0.9343352913856506),
 (2996, 0.6761938333511353),
 (2997, 0.9732835292816162),
 (3001, 0.9827924370765686),
 (3002, 0.9775826334953308),
 (3006, 0.9567468166351318),
 (3009, 0.9300262331962585),
 (3019, 0.8803578019142151),
 (3020, 0.6879516839981079),
 (3023, 0.9997181296348572),
 (3027, 0.9986199140548706),
 (3034, 0.5094358921051025),
 (3035, 0.8353139162063599),
 (3039, 0.643153965473175),
 (3043, 0.975822925567627),
 (3048, 0.7647864818572998),
 (3051, 0.6987146139144897),
 (3057, 0.9968504309654236),
 (3059, 0.8400719165802002),
 (3068, 0.9978815913200378),
 (3071, 0.9948340654373169),
 (3079, 0.9757486581802368),
 (3084, 0.8929972648620605),
 (3087, 0.993901252746582),
 (3093, 0.9990550875663757),
 (3096, 0.5478706955909729),
 (3106, 0.9971812963485718),
 (3111, 0.9899482727050781),
 (3113, 0.9984717965126038),
 (3118, 0.9942716360092163),
 (3121, 0.7945055961608887),
 (3123, 0.6986526250839233),
 (3124, 0.9913369417190552),
 (3145, 0.9656509757041931),
 (3150, 0.9914391040802002),
 (3151, 0.9960684776306152),
 (3152, 0.9917894601821899),
 (3155, 0.9941934943199158),
 (3161, 0.997941792011261),
 (3175, 0.9294313788414001),
 (3176, 0.9798362255096436),
 (3177, 0.9991764426231384),
 (3178, 0.9954239726066589),
 (3184, 0.999447762966156),
 (3198, 0.8378008008003235),
 (3201, 0.997536301612854),
 (3202, 0.9425883889198303),
 (3204, 0.9959760308265686),
 (3205, 0.996131420135498),
 (3208, 0.614535927772522),
 (3212, 0.9333183169364929),
 (3216, 0.6808130145072937),
 (3218, 0.9914149641990662),
 (3219, 0.5310062766075134),
 (3221, 0.9758943319320679),
 (3227, 0.9360953569412231),
 (3242, 0.9897779822349548),
 (3247, 0.9800073504447937),
 (3249, 0.5625650882720947),
 (3251, 0.8727046251296997),
 (3257, 0.9967677593231201),
 (3259, 0.9890537261962891),
 (3263, 0.9959522485733032),
 (3272, 0.9750798344612122),
 (3273, 0.9830127358436584),
 (3287, 0.9641245007514954),
 (3289, 0.999167799949646),
 (3290, 0.955521821975708),
 (3291, 0.9637478590011597),
 (3292, 0.9994575381278992),
 (3294, 0.9366588592529297),
 (3295, 0.756989598274231),
 (3303, 0.9997580647468567),
 (3313, 0.9997339844703674),
 (3329, 0.9265108704566956),
 (3333, 0.6798418164253235),
 (3340, 0.9196746349334717),
 (3345, 0.8705523014068604),
 (3354, 0.9368694424629211),
 (3359, 0.999161958694458),
 (3367, 0.9924915432929993),
 (3377, 0.9986867308616638),
 (3380, 0.8725317120552063),
 (3389, 0.99708491563797),
 (3393, 0.9671447277069092),
 (3394, 0.9968008995056152),
 (3397, 0.9907221794128418),
 (3399, 0.9536487460136414),
 (3409, 0.9641170501708984),
 (3411, 0.9996398687362671),
 (3414, 0.9990758895874023),
 (3416, 0.9256104230880737),
 (3433, 0.7595140337944031),
 (3458, 0.9867621064186096),
 (3460, 0.9905164837837219),
 (3463, 0.9942798614501953),
 (3464, 0.9996987581253052),
 (3478, 0.9994710087776184),
 (3492, 0.9996570348739624),
 (3493, 0.9992375373840332),
 (3495, 0.999470055103302),
 (3509, 0.9978559613227844),
 (3515, 0.9935274720191956),
 (3519, 0.9961732029914856),
 (3520, 0.9935798645019531),
 (3526, 0.927002489566803),
 (3533, 0.9932505488395691),
 (3547, 0.9949727058410645),
 (3549, 0.9521857500076294),
 (3550, 0.9990723133087158),
 (3554, 0.9897067546844482),
 (3560, 0.901516854763031),
 (3566, 0.9932146072387695),
 (3568, 0.9990917444229126),
 (3571, 0.9693847894668579),
 (3572, 0.9984678626060486),
 (3574, 0.5863868594169617),
 (3577, 0.9991419315338135),
 (3582, 0.97563236951828),
 (3583, 0.9997032284736633),
 (3595, 0.9725579619407654),
 (3606, 0.991844117641449),
 (3619, 0.9893956780433655),
 (3630, 0.7203545570373535),
 (3646, 0.9921992421150208),
 (3648, 0.9328567385673523),
 (3656, 0.9936655163764954),
 (3660, 0.887725830078125),
 (3661, 0.8239907622337341),
 (3667, 0.9566008448600769),
 (3669, 0.9950227737426758),
 (3684, 0.994224488735199),
 (3687, 0.9989280104637146),
 (3694, 0.847058892250061),
 (3695, 0.9967067837715149),
 (3697, 0.9949199557304382),
 (3702, 0.99573814868927),
 (3708, 0.9519678950309753),
 (3747, 0.9384403228759766),
 (3758, 0.9891999959945679),
 (3771, 0.9309841990470886),
 (3777, 0.979459822177887),
 (3789, 0.9978267550468445),
 (3792, 0.9957621693611145),
 (3793, 0.998314380645752),
 (3799, 0.856451690196991),
 (3818, 0.998979389667511),
 (3837, 0.9788182973861694),
 (3854, 0.9945323467254639),
 (3860, 0.8836297392845154),
 (3864, 0.9076529145240784),
 (3871, 0.9975602626800537),
 (3877, 0.996767520904541),
 (3881, 0.9998366832733154),
 (3892, 0.9985038042068481),
 (3896, 0.9897077083587646),
 (3899, 0.8049295544624329),
 (3908, 0.9989314675331116),
 (3910, 0.9992853999137878),
 (3917, 0.9993558526039124),
 (3927, 0.9990293979644775),
 (3931, 0.9812543392181396),
 (3944, 0.9513840079307556),
 (3948, 0.9943537712097168),

In [26]:
confusing_samples = [dataset["test"][i] for i, score in idxs_scores if score <= 0.7]

In [41]:
len(confusing_samples)

203

In [27]:
confusing_samples

[{'ID': 65,
  'text': 'I had such a nice day. Too bad the rain comes in tomorrow at 5am',
  'label': 'negative'},
 {'ID': 238,
  'text': '@CaitlinOConnor i want tacos and margarhitas  telll gay i say hello&lt;3',
  'label': 'negative'},
 {'ID': 263,
  'text': 'help me forget 8th april &amp; 13th july!',
  'label': 'negative'},
 {'ID': 315,
  'text': "My thoughts are with Sandra Cantu's family at this difficult and sad time",
  'label': 'negative'},
 {'ID': 359,
  'text': "I don't understand why things get taken away. I didn't have enough time with him its unfair. I want him back!! He was like my baby",
  'label': 'negative'},
 {'ID': 664,
  'text': 'im sooo sad right now  i need a hug',
  'label': 'negative'},
 {'ID': 698,
  'text': 'iLearn is down and out, great considering finals are this week...',
  'label': 'negative'},
 {'ID': 730, 'text': "Can't sleep again", 'label': 'negative'},
 {'ID': 1012, 'text': '@citizensheep', 'label': 'negative'},
 {'ID': 1013,
  'text': '@thesage1014 I wish I could! Gotta work though',
  'label': 'negative'},
 {'ID': 1096,
  'text': '@henrygooden @oddchicken I went there about a month and a half ago, was still open then. Smelt really good, but I was getting sick',
  'label': 'negative'},
 {'ID': 1097,
  'text': 'is ready to go to bed..long day tomorrow',
  'label': 'negative'},
 {'ID': 1251,
  'text': '@Weebeedee run was great thanks. Is very windy today so bike ride not an option this morning',
  'label': 'negative'},
 {'ID': 1340,
  'text': '@PaulTeeter we passed by the border',
  'label': 'negative'},
 {'ID': 1373,
  'text': 'doing some business studies revision',
  'label': 'negative'},
 {'ID': 1419,
  'text': 'My stomach is feeling satisfied now......been starving for 2 hours.',
  'label': 'negative'},
 {'ID': 1486,
  'text': '@Gen_Marie  I hope we can fix you in California at least.....',
  'label': 'negative'},
 {'ID': 1513,
  'text': 'Just wrote a 2 pg paper n 30 min, studied n now off 2 bed. Gotta wake up n 3 hours. OH JOY!  Nite all!',
  'label': 'negative'},
 {'ID': 1567,
  'text': "@CandiceNicolePR I haven't heard from you in while",
  'label': 'negative'},
 {'ID': 1597,
  'text': 'all these crazy pollen trees in Washington state are making my sinuses go crazy',
  'label': 'negative'},
 {'ID': 1665,
  'text': '@eri74 Goodmorning!  hahaha, let me guess .... CB? hahaha me not',
  'label': 'negative'},
 {'ID': 1680,
  'text': 'has just said goodbye to her hubby who is off globe trotting away',
  'label': 'negative'},
 {'ID': 1877, 'text': '@shantelleb so has mine', 'label': 'negative'},
 {'ID': 2044,
  'text': '@sianllewellyn ive txt you this morning',
  'label': 'negative'},
 {'ID': 2142,
  'text': 'Prodigy were ace last night! Only managed a few hours sleep last night, not feeling myself today        Have a cool day guys.',
  'label': 'negative'},
 {'ID': 2358,
  'text': "Maya is being spayed today.I'm very nervous about it",
  'label': 'negative'},
 {'ID': 2410,
  'text': 'its day one of my ivf injections so let the fun begin',
  'label': 'negative'},
 {'ID': 2641,
  'text': "@fabianv what kind of docs? and what are you using to write them? we're always behind on our docs",
  'label': 'negative'},
 {'ID': 2649,
  'text': "it's mums birthday, im glad she likes her pressies. i'm looking forward to party time later this week, but sad im not going to cornwall",
  'label': 'negative'},
 {'ID': 2650,
  'text': '@dajbelshaw sounds like my every day  except gym',
  'label': 'negative'},
 {'ID': 2682,
  'text': 'Needs to go to the dentist now. What a perfect start for the holidays,hm?',
  'label': 'negative'},
 {'ID': 2779, 'text': 'I really hope I suceed', 'label': 'negative'},
 {'ID': 2835, 'text': 'I hope not all is lost *sigh*', 'label': 'negative'},
 {'ID': 2900,
  'text': '@swati121 yeah i havnt got any crad/unlimited to text/call either  sucks. will catch up with you today sometime!! xxxxx',
  'label': 'negative'},
 {'ID': 2997,
  'text': 'just got up, pshhh going on the trampoline, even though I am all sore',
  'label': 'negative'},
 {'ID': 3021,
  'text': '@Donniesbabe well its pishing here  sun looks like it wants to break through hope it dows kids doing my head in !!!!!!',
  'label': 'negative'},
 {'ID': 3035,
  'text': 'Twitter was down when I went to bed last night.   But now it back and so am I!',
  'label': 'negative'},
 {'ID': 3040,
  'text': '@redtoffee Strawberry is the absolute best Angel Delight EVA!  I had chocolate once, but it was too sweet.',
  'label': 'negative'},
 {'ID': 3052,
  'text': 'a day of nothing...bliss!! miss my boy tho',
  'label': 'negative'},
 {'ID': 3097,
  'text': "Driving to my parents and chilling with them. Well the sun is shining, but I don't feel so well today",
  'label': 'negative'},
 {'ID': 3124,
  'text': '@cadelofficial http://twitpic.com/2ved8 - I love mountains.. but i live in belgium..',
  'label': 'negative'},
 {'ID': 3209,
  'text': "@binncheol  you should listen to some music by this dude called andy hull and afew other blokes. I even hear they're playing ldn tomorrow!",
  'label': 'negative'},
 {'ID': 3217,
  'text': "@FrumiousMe T'was the antibiotics for root canal.  Will take Polaramine tonight for hives, other symptoms have gone now thank goodness.",
  'label': 'negative'},
 {'ID': 3220,
  'text': "yep...it's been 6 weeks  A lady at our church is watching her.",
  'label': 'negative'},
 {'ID': 3250,
  'text': 'Red Jaguars, Blue Barracudas, Green Monkeys, Orange Iguanas, Purple Parrots and Silver Snakes... remember Legends of the Hiddent Temple?',
  'label': 'negative'},
 {'ID': 3334,
  'text': "@missymoouk Oh No!!  I know. I haven't cried that much since Wham split up.....",
  'label': 'negative'},
 {'ID': 3575,
  'text': "@sneffielynn I wish I knew what's going on with TB.  It's driving me crazy.",
  'label': 'negative'},
 {'ID': 3969,
  'text': "@Sixxjohn I'm the worst I know  but I'll be back soon",
  'label': 'negative'},
 {'ID': 4196,
  'text': 'Enjoyed Wrestlemania and would much rather be at home then being stuck at work',
  'label': 'negative'},
 {'ID': 4208,
  'text': "@AbbieLeona_Ox Liverpool. Don't get me jealous  going to london on thursdaiii",
  'label': 'negative'},
 {'ID': 4341, 'text': 'So near yet so far.', 'label': 'negative'},
 {'ID': 4347,
  'text': '@cuzza that sounds almost as good as nandos ;-) related; nandos have increased prices again',
  'label': 'negative'},
 {'ID': 4362,
  'text': 'I miss Angiii  I miss talking too her  I love you Angiii!',
  'label': 'negative'},
 {'ID': 4482,
  'text': '@KevAnthony let me give you a hug, its cold here too',
  'label': 'negative'},
 {'ID': 4634,
  'text': "@foxiehaha haven't heard from her today",
  'label': 'negative'},
 {'ID': 4700,
  'text': "@emmabush Well, I didn't mention the stale Peeps.",
  'label': 'negative'},
 {'ID': 4703,
  'text': "@lisiepeasie I'm supposed to be the one who falls in love with cute French ladies.",
  'label': 'negative'},
 {'ID': 4712, 'text': "@Zanna85 i don't like that day", 'label': 'negative'},
 {'ID': 4722, 'text': '@j_e_p  me too', 'label': 'negative'},
 {'ID': 4802,
  'text': '@kristenkreuk Hey Kristen, thought ur work on Smallville was awesome, havnt seen SF (not released in Aus yet)  Any new projects coming up?',
  'label': 'negative'},
 {'ID': 4923,
  'text': "@bramstadhouders It's easier to feel connected through mutual pain. It's closer to the general level of consciousness of most people..",
  'label': 'negative'},
 {'ID': 5100,
  'text': '@airbush  thanks for the guru links, but they just take me to the sign in page',
  'label': 'negative'},
 {'ID': 5196,
  'text': "Going to starbucks!! Then school  first period is French. Zut! Je n'a pas fait mes devoirs francais.",
  'label': 'negative'},
 {'ID': 5207,
  'text': '@KikitaLinda Awww but 300 is also very much =D oh my gosh do you know whats going on with nick?',
  'label': 'negative'},
 {'ID': 5244,
  'text': '@roseformyrose oh I am feeling the same today',
  'label': 'negative'},
 {'ID': 5318,
  'text': "@Rockergirl75 Eeek, I wanna read now but I can't  Later, I'll be on there later *can't wait*",
  'label': 'negative'},
 {'ID': 5583,
  'text': "@nessie111 think it's over here babe",
  'label': 'negative'},
 {'ID': 5594,
  'text': "Well I'm gonna go get ready for school, then I'm going to school",
  'label': 'negative'},
 {'ID': 5626,
  'text': '@LorettaK @HeatherShorter Seriously though - there are 6 pairs of shoes in that fedex box, all bought recently',
  'label': 'negative'},
 {'ID': 5712,
  'text': 'My macBook is behaving very strangely....',
  'label': 'negative'},
 {'ID': 5929,
  'text': 'Trying to get rid of brightness and alphas in Flash. File keeps exporting with the brightness and alpha in tact.',
  'label': 'negative'},
 {'ID': 5949,
  'text': 'Really liking the new Yahoo Music Pages http://new.music.yahoo.com/velvet-underground. The only problem is that it uses Rhapsody',
  'label': 'negative'},
 {'ID': 5969, 'text': 'off 2 work soon', 'label': 'negative'},
 {'ID': 6061,
  'text': "@Kal_Penn The episode broke my heart, even though we'd speculated that this was what was coming   Will miss you terribly on the show.",
  'label': 'negative'},
 {'ID': 6101,
  'text': "@GirlsGoneChild i'm sorry... go hold that little fable and inhale. feel better, sweet rebecca...",
  'label': 'negative'},
 {'ID': 6144,
  'text': '@brendonbossy i reckon! im wearing bed socks for the first time this year  boooooooo to winter',
  'label': 'negative'},
 {'ID': 6196,
  'text': '@giznad definitely, too bad it is so clearly about Judith Marie Keenan  Pretty cool though',
  'label': 'negative'},
 {'ID': 6260, 'text': 'version near where I live.', 'label': 'negative'},
 {'ID': 6282, 'text': '@stualpha work to be done first', 'label': 'negative'},
 {'ID': 6916, 'text': 'i feel like i need a hug.', 'label': 'negative'},
 {'ID': 6977,
  'text': 'Wishes everyone understood the concept of bathing, and wearing clean clothes',
  'label': 'negative'},
 {'ID': 7117, 'text': '@jltorrent I know', 'label': 'negative'},
 {'ID': 7139,
  'text': 'was late to work and hopes she is not in trouble...',
  'label': 'negative'},
 {'ID': 7171, 'text': '@McFlyRule so am i!', 'label': 'negative'},
 {'ID': 7354, 'text': 'It official, I have strep throat', 'label': 'negative'},
 {'ID': 7445,
  'text': "@ShannonHerod Oh noooooo.....That is horrible.  Pets are our babies - our family members. It's never easy. I'm thinking of u - be strong.",
  'label': 'negative'},
 {'ID': 7533,
  'text': 'weight training,humanities,astronomy x2,math - guitar ; last day of sunshine  &lt;3',
  'label': 'negative'},
 {'ID': 7603,
  'text': 'Meeting for the next couple hours about automated building control systems',
  'label': 'negative'},
 {'ID': 7705,
  'text': "I love it when class gets cancelled! Too bad it's my 2nd of 3 classes of the day so I still have to stay for my 1st &amp; last ones",
  'label': 'negative'},
 {'ID': 7750,
  'text': "@CuddlyDragon Heading back home on Thursday evening after work I'm afraid.",
  'label': 'negative'},
 {'ID': 7813,
  'text': 'Every single photo I have taken today is butters',
  'label': 'negative'},
 {'ID': 7864,
  'text': 'Good morning everyone .... Rob is trying to pull his foot out of his mouth this morning',
  'label': 'negative'},
 {'ID': 7984, 'text': "wishes he wasn't ill", 'label': 'negative'},
 {'ID': 8121,
  'text': "@UrfavoriteBarbi what's good with u this morning. laundry day for me  when i get more doe, i'm droppin everything at the cleaners.",
  'label': 'negative'},
 {'ID': 8232, 'text': 'not more rain', 'label': 'negative'},
 {'ID': 8498,
  'text': "Dear April Hall, if you didn't mary Toby Alvillar I may just SCREAM. Although Ken Kamata needs the love  Sheesh.",
  'label': 'negative'},
 {'ID': 8533, 'text': '@peteeee work  then who knows', 'label': 'negative'},
 {'ID': 8625,
  'text': "@TheWordsmith @soultapestry  I don't think I'm objectifiable at this point",
  'label': 'negative'},
 {'ID': 8710, 'text': '@ileandeezy me too', 'label': 'negative'},
 {'ID': 8766,
  'text': 'im lonely  keep me company! 22 female, Jacksonville - Florida',
  'label': 'negative'},
 {'ID': 8828,
  'text': '@zionxpress  Soon though? Will you join him on the road then?',
  'label': 'negative'},
 {'ID': 8948,
  'text': '@Strabismus I assume you live in the Midwest? I watch Jimmy every night, I miss Conan',
  'label': 'negative'},
 {'ID': 8964,
  'text': "@iamjonathancook thanks, now that's going to be in my head all night. i'm upset you never gave me my other wishes yet,",
  'label': 'negative'},
 {'ID': 9014,
  'text': '@evansamantha @janetastic thanks for the tip! no ff for us this weekend.',
  'label': 'negative'},
 {'ID': 9040,
  'text': "I still have major belly itch. Bummer. Dagger is getting a haircut tomorrow. It's cold in my apartyment. My toilet won't stop running",
  'label': 'negative'},
 {'ID': 9042,
  'text': "Headahes and scary nightmares!!! Ahhhh don't wanna fall asleep",
  'label': 'negative'},
 {'ID': 9065,
  'text': '@Jon_Aston Thanks for the retweet &amp; subsequent retweets Jon. I hope to goodness they find her. I think the cops bungled things early on',
  'label': 'negative'},
 {'ID': 9086,
  'text': 'aww one of the lil chicks just yawned, they will be going home tomorrow',
  'label': 'negative'},
 {'ID': 9264,
  'text': '@singswell aww that sucks.   get well soon sweetie.',
  'label': 'negative'},
 {'ID': 9302,
  'text': "@laurie  I get like that too. But then I miss it. it's so complicated lol. At least I can still see you here!",
  'label': 'negative'},
 {'ID': 9344,
  'text': 'I just bawled my eyes out watching Marley and me.',
  'label': 'negative'},
 {'ID': 9396,
  'text': 'managed to wake up early today @8..feeling sleepy again..',
  'label': 'negative'},
 {'ID': 9549,
  'text': '@lauren42 hope Yall have fun without me tomorrow. Im so jealous and mad i cant go.',
  'label': 'negative'},
 {'ID': 9623,
  'text': '@nancyalexandria LOL im trying to be too but for basktball but idk i like it  sometimes LOL',
  'label': 'negative'},
 {'ID': 9726,
  'text': '@jllg15 where were youu?? hahaa my only friends here  haha LMAOOO! this thing really is popular but I sitll cant figure comethings out',
  'label': 'negative'},
 {'ID': 9742,
  'text': 'havent been on all day  hanging out with my mommy&lt;3',
  'label': 'negative'},
 {'ID': 9826,
  'text': "@technicalwriter aka St George's Day - the universally uncelebrated National Day of England",
  'label': 'negative'},
 {'ID': 10048,
  'text': '...aaaand there goes that great day  RIP Mrs Wever',
  'label': 'negative'},
 {'ID': 10057,
  'text': "@whit3boy I couldn't walk last night like wth",
  'label': 'negative'},
 {'ID': 10106,
  'text': 'So many new followers from #followfriday! Welcome everyone! usually I send a message to each, but was on deadline yesterday.',
  'label': 'negative'},
 {'ID': 10144,
  'text': '@Bootley aww, that sux!! get some rest and drink plenty of water. feel better',
  'label': 'negative'},
 {'ID': 10258,
  'text': "@holypotato dude I can't go back to sleep",
  'label': 'negative'},
 {'ID': 10302, 'text': 'me wants beach', 'label': 'negative'},
 {'ID': 10412,
  'text': '@3SillyDogs It is nice here too, 50s, but the temps are going to drop today',
  'label': 'negative'},
 {'ID': 10590,
  'text': 'aephi picnic then some major studying at hillman',
  'label': 'negative'},
 {'ID': 10626, 'text': '@wichitarecs', 'label': 'negative'},
 {'ID': 10637,
  'text': "@collective_soul I really tried to recruit as many people as I could to follow you guys so you wouldn't lose $500.00!",
  'label': 'negative'},
 {'ID': 10701,
  'text': "Studying for a final...too bad it's beautiful outside",
  'label': 'negative'},
 {'ID': 10731, 'text': 'Work work work! no play today', 'label': 'negative'},
 {'ID': 10732,
  'text': 'Apparently One is not to take a B12 pill without eating first lol',
  'label': 'negative'},
 {'ID': 10786,
  'text': 'rainy day   clean house I guess...',
  'label': 'negative'},
 {'ID': 10814,
  'text': "understands that he doesn't want to talk right now",
  'label': 'negative'},
 {'ID': 10844,
  'text': "i'm trying to do my work  and watching come dine with me",
  'label': 'negative'},
 {'ID': 10861, 'text': 'work again in 25 mins', 'label': 'negative'},
 {'ID': 10941,
  'text': "I'm feeling groggy, sore, and a little sick. Good morning  haha! What's the word, Twitter?",
  'label': 'negative'},
 {'ID': 10947,
  'text': "UGH tequila got the best of me, I'm sorry @_miss_mj  but we are ON for tomorrow, don't let me drink tequila! @EStrangeNoise ride ovr latr!",
  'label': 'negative'},
 {'ID': 11162,
  'text': "@BriggySmalls - won't be able to make it   Got stuck running around! Have a pint for me! I'll see you on monday. Go gunners",
  'label': 'negative'},
 {'ID': 11249,
  'text': '@Tiffheartzero yeah, apparently so. I noticed a ring on his finger at the show',
  'label': 'negative'},
 {'ID': 11281,
  'text': "my best friend from high school can't come to my wedding or be in my bridal party anymore",
  'label': 'negative'},
 {'ID': 11316,
  'text': 'didnt get to go to the party last night',
  'label': 'negative'},
 {'ID': 11527,
  'text': "Mummy isn't coming home this weekend.    *pout*",
  'label': 'negative'},
 {'ID': 11541,
  'text': 'Very sad - Charlton Athletic have been relegated.  Will have a drink to console myself',
  'label': 'negative'},
 {'ID': 11581,
  'text': "@Juana4ev alas it won't be bikini season for me...maybe in 20 years",
  'label': 'negative'},
 {'ID': 11589,
  'text': 'Sexy Saturday...but unfortunately i cant enjoy it Im stuck here studyyin....',
  'label': 'negative'},
 {'ID': 11591,
  'text': "@Faz4980 yeah, but i can be glad to have work. here and there i'm looking for job offers, but there are no good ones",
  'label': 'negative'},
 {'ID': 11694,
  'text': '@Chocolatedrop88 kno how to work n e thing  so I jus went bak upstairs n did sit ups but later I played tennis 4 2 hrs, yay me!!',
  'label': 'negative'},
 {'ID': 11714,
  'text': "@RiskyBusinessMB i wish i could go to san diego today  but i've got to work today",
  'label': 'negative'},
 {'ID': 11716,
  'text': 'just got back from visiting with a foster dog.  we have so many pugs looking for homes!!   www.gmpr.org take a look!!',
  'label': 'negative'},
 {'ID': 11892,
  'text': '@jAD0ReQUi thanks qui qui .. Yeh no bueno',
  'label': 'negative'},
 {'ID': 12051,
  'text': "@myimpretentious thank you angel!  it's a shame you can't change the white of the tweet background",
  'label': 'negative'},
 {'ID': 12093, 'text': 'cleaningg', 'label': 'negative'},
 {'ID': 12263,
  'text': "I work all week and I'm fine. Saturday I wake up... I'm so sick  WTF",
  'label': 'negative'},
 {'ID': 12324,
  'text': 'I hate being yelled at everyone hates me today',
  'label': 'negative'},
 {'ID': 12346,
  'text': "http://twitpic.com/3j4ct Lots of love for Jake! I call this my pre &quot;don't leave&quot; tactic.. Lol",
  'label': 'negative'},
 {'ID': 12353,
  'text': 'at my last cheer competition for senior L4',
  'label': 'negative'},
 {'ID': 12437,
  'text': "@HeroesforAutism I wish I could go, but I'm in Montreal. Other side of the continent",
  'label': 'negative'},
 {'ID': 12563,
  'text': "@amazingphoebe i have to be up in three hours time, so i'm going to try and get some sleep. i'll talk to you later, i guess  night xxxx",
  'label': 'negative'},
 {'ID': 12647,
  'text': 'I am officially finished for the winter season 1 more week of snow',
  'label': 'negative'},
 {'ID': 12701,
  'text': "@burningsound but that's kind of iffy for me too because my internet is up and down because of the weather too",
  'label': 'negative'},
 {'ID': 12726,
  'text': 'is at the most awk/nerdy history luncheon ev  fml',
  'label': 'negative'},
 {'ID': 12739, 'text': 'My mouth is now on fire', 'label': 'negative'},
 {'ID': 12923,
  'text': 'Finished garden for today. Hey fever broke out finally',
  'label': 'negative'},
 {'ID': 12947,

In [ ]:
ppl("More rain.  Its not fun to be stuck inside with two kids with unending energy.")

[{'label': 'POSITIVE', 'score': 0.6779118180274963}]

In [47]:
dataset["test"][-10]

{'ID': 1599991, 'text': 'WOOOOO! Xbox is back', 'label': 'positive'}

In [48]:
ppl('WOOOOO! Xbox is back')

[{'label': 'NEGATIVE', 'score': 0.9324511885643005}]

In [ ]:
from hydra import compose, initialize
from omegaconf import OmegaConf

# Initialize Hydra
initialize(version_base="1.3", config_path="config")

# Compose the configuration
cfg = compose(config_name="unsupervised")

# Print the config
print(OmegaConf.to_yaml(cfg))

method:
  _target_: src.methods.TopologicalEntropy
  model_name: ${model_name}
  dtype: float32
  device: cuda
  cache_dir: cache/topological_entropy_8_09
  generated_responses_dir: cache/generated_responses_8_09_15
  num_return_sequences: 15
  temperature: 1.0
  max_new_tokens: 256
preprocess:
  _target_: src.preprocess.SQuAD
  model_name: ${model_name}
  source_dir: data/fixed/SQuAD
  val_size: 150
  random_state: 42
transfer:
  _target_: src.preprocess.SQuAD
  source_dir: data/fixed/SQuAD
  val_size: 150
  random_state: 42
evaluation:
  seed: 42
  k: 5
  test_size: 0.25
  val_size: 100
model_name: Llama-2-7b-chat-hf
transfer_names:
- squad

In [3]:
from hydra.utils import instantiate

In [4]:
dataset = instantiate(cfg["preprocess"])
X, y, _, _ = dataset.process()

In [5]:
X

,id,prompt,response,name
0,5725d662ec44d21400f3d68b,"<s> [INST] Given the context, answer the quest...",Kearney Park hosts the largest Civil War reen...,squad
1,57280f974b864d1900164372,"<s> [INST] Given the context, answer the quest...",Civil disobedience is typically defined as th...,squad
2,5725f5b1271a42140099d374,"<s> [INST] Given the context, answer the quest...",Most of the wind in Fresno originates from th...,squad
3,572751b4708984140094dc1b,"<s> [INST] Given the context, answer the quest...",A complex net of contracts and other legal ob...,squad
4,5726400589a1e219009ac5ef,"<s> [INST] Given the context, answer the quest...",The small tentacles on Cydippids are called t...,squad
...,...,...,...,...
795,573010fab2c2fd14005687da,"<s> [INST] Given the context, answer the quest...",Algeria,squad
796,572ffee1947a6a140053cf15,"<s> [INST] Given the context, answer the quest...",The All India Muslim League.,squad
797,57282358ff5b5019007d9dde,"<s> [INST] Given the context, answer the quest...","According to the given context, Jacksonville'...",squad
798,5725c071271a42140099d12b,"<s> [INST] Given the context, answer the quest...",It joined the easterly flow toward the Atlantic.,squad
799,572ffc99947a6a140053cefa,"<s> [INST] Given the context, answer the quest...",Sadat was rewarded by the Islamists for his a...,squad

In [6]:
import joblib

In [7]:
data = joblib.load("/app/cache/generated_responses_8_09_15/Llama-2-7b-chat-hf_6ba1391fbd3aa874b19179b3404cbf74_generated_responses.joblib")

In [9]:
X["gen_responses"] = data

In [13]:
X["topo_entropy"] = joblib.load("/app/cache/topological_entropy_8_09_0.1_graph/Llama-2-7b-chat-hf_ab2aabd38763db812b6a0c964d9918a9_topological_entropy.joblib")["topo_entropy"]

In [25]:
data_2 = joblib.load("/app/cache/generated_responses_8_09_15/Llama-2-7b-chat-hf_fd8ecfe6a895efac995650f458080ed4_generated_responses.joblib")

In [26]:
data_2

[[' After experiencing a premature birth and spending 14 weeks in the hospital, Leanne Hughes and her partner Dale Davies are hoping to take their son Jude home on Monday, weighing 6lb 1oz. They have been involved in trialing specialist equipment for a new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs, to help make the experience more comfortable for other parents.</s>',
  ' After 14 weeks in the hospital, Leanne Hughes and her partner Dale Davies are hoping to take their premature baby boy, Jude, home on Monday. They have been involved in testing specialized equipment for a new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs, which has helped them feel more confident and comfortable caring for Jude. Despite the challenges, they are grateful for the excellent care they have received from the staff and hope to start their life together as a family soon.</s>',
  ' After experiencing a bleed at 24 weeks pregnant, Leanne Hughes was transferred to Preston hospital for six weeks before being transferred back to Glan Clwyd hospital, where she gave birth to her premature baby boy, Jude, at 29 weeks. Jude spent 14 weeks in hospital before he and his parents hope to go home on Monday, where he will continue to receive oxygen support until he is more settled. Leanne and her partner, Dale, have been involved in trialing new equipment for the neonatal intensive care centre in Denbighshire, including incubators and breastfeeding chairs, which has helped them feel more comfortable and confident in caring for their baby.</s>',
  ' After 14 weeks in the hospital, Leanne Hughes and her partner Dale Davies are hoping to take their son Jude home on Monday, weighing 6lb 1oz. They have been involved in trialing specialist equipment for a new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs, to help other parents have a more comfortable experience. Despite the challenges, they are grateful for the excellent care their son has received from the staff and hope to start their life together soon.</s>',
  " After experiencing a bleed at 24 weeks pregnant, Leanne Hughes was transferred to Preston hospital for six weeks, where her son Jude was born prematurely at 28 weeks and 6 pounds 1 ounce. The family is now hoping to take Jude home to Connah's Quay on Monday, 14 weeks after being admitted to the hospital, and have been involved in trialing specialist equipment for a new neonatal intensive care center in Denbighshire.</s>",
  " After 14 weeks in the hospital, Leanne Hughes and Dale Davies' baby Jude has increased his weight to 6lb 1oz and they are hoping to take him home to Connah's Quay on Monday. They have been involved in trialing specialist equipment for a new neonatal intensive care center in Denbighshire, including incubators and chairs for breastfeeding, and have found it helpful in their journey. Despite the challenges, they are grateful for the staff's care and support, and hope to start their life together soon.</s>",
  ' A couple, Leanne Hughes and Dale Davies, are hoping to take their premature baby boy, Jude, home from the hospital after 14 weeks in care. They have been involved in trialing specialist equipment for a new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs, to help other parents in similar situations.</s>',
  " A baby boy named Jude was born prematurely at 24 weeks and has been in the neonatal intensive care unit (NICU) for six weeks, during which his parents Leanne and Dale tested specialist equipment for a new NICU in Denbighshire. Despite the initial bleed and water breaking, Jude has pulled through and his parents are hoping to take him home to Connah's Quay on Monday, 14 weeks after his birth.</s>",
  ' After 14 weeks in the hospital, Leanne Hughes and her partner Dale Davies are hoping to take their premature baby boy, Jude, home on Monday, August 22. Jude was born at 24 weeks and has been in the hospital for six weeks before being transferred to another hospital for further care. Leanne and Dale are participating in a trial for specialist equipment for a new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs, to help other parents going through a similar experience. Despite the challenges, the staff at the hospital have been amazing and have looked after them well.</s>',
  " After 14 weeks in the hospital, Leanne Hughes and Dale Davies' baby, Jude, is expected to come home on Monday. Jude was born prematurely at 24 weeks and has been in the neonatal intensive care unit, where he has been receiving specialized equipment to help him grow and thrive. Leanne and Dale have been actively involved in trial testing the equipment, including incubators and breastfeeding chairs, to help make the experience more comfortable for other parents. Despite the challenges, they are hopeful for Jude's future and the prospect of starting their life together as a family.</s>",
  ' A premature baby boy named Jude was born at 24 weeks and has been in the neonatal intensive care unit for six weeks, during which time his parents Leanne and Dale have been involved in trialing specialist equipment for a new neonatal center in Denbighshire, Wales. Despite the challenges, Jude has pulled through and is expected to come home on Monday, 19 August, 14 weeks after his birth.</s>',
  " A premature baby boy, Jude, was born at 24 weeks and has spent 14 weeks in the hospital neonatal intensive care unit in Preston, Wales, along with his parents, Leanne and Dale. They are hopeful to take him home on Monday, and have been involved in trialing specialist equipment for the hospital's new neonatal center, including incubators and breastfeeding chairs. Despite the challenges, the staff have been amazing and have made them feel welcome during their time in the hospital.</s>",
  " After 14 weeks in the hospital, 6-pound 1-ounce baby Jude is expected to go home with his parents Leanne Hughes and Dale Davies on Monday. While in the hospital, they have been involved in testing specialized equipment for the new neonatal intensive care center in Denbighshire, including incubators and breastfeeding chairs. Despite the challenges they have faced, the parents remain positive and hopeful for their baby's future.</s>",
  " Leanne Hughes and her partner Dale Davies' baby Jude was born prematurely at 24 weeks and has been in hospital for six weeks before being transferred back to their local hospital, Glan Clwyd, where they are currently staying for Leanne to breastfeed and trial new neonatal equipment. Despite the challenges, they remain positive and hope to take Jude home on Monday.</s>",
  ' After experiencing a bleed during her pregnancy, Leanne Hughes was transferred to a neonatal intensive care unit in Preston, where she spent six weeks before being transferred back to her local hospital in Glan Clwyd. She and her partner, Dale Davies, have been involved in trialing specialist equipment for the new neonatal intensive care centre in Denbighshire, including incubators and breastfeeding chairs, and are hoping to take their son, Jude, home on Monday, 19 weeks after his birth.</s>'],
 [" Someone ripped up copies of the Islamic holy book, the Koran, in three toilet bowls at a Texas university, prompting an investigation and concern from students and administrators, despite the university's commitment to religious and ethnic diversity.</s>",
  " Someone ripped up copies of the Islamic holy book, the Koran, in three toilet bowls at a Texas university, prompting an investigation and concern from the school's Muslim community, despite a statement from student senators calling it an isolated incident.</s>",
  ' Local media outlets have shared photos of copies of the Islamic holy book, the Koran, found in three toilet bowls at a Texas university, leading campus police to investigate the incident as "strange" and "very unusual," with security footage being reviewed to identify one of six people seen entering the toilet on the evening of the incident, despite a reflection room where multi-faith prayer books are kept being untouched, and with the university\'s Muslim Student Association president describing the case as "definitely saddening and a little disturbing," while the student senators have released a statement calling it an isolated incident that does not represent the university community.</s>',
  " Local media photos showed copies of the Islamic holy book in three toilet bowls at a Texas university, prompting an investigation by campus police, who are trying to identify one of six people seen entering the toilet on the evening of the incident, despite the university's multifaith environment and overwhelming support from students.</s>",
  ' Local media have shared photos of copies of the Islamic holy book, the Koran, found in three toilet bowls at a university in Texas, leading to an investigation by campus police, who are trying to identify a suspect and have been reviewing security footage.</s>',
  ' Six copies of the Islamic holy book, the Koran, were found torn up and scattered in three toilet bowls at a college campus in Texas, prompting an investigation and condemnation from university officials and the local Muslim community.</s>',
  ' Local media have shared photos of copies of the Islamic holy book, the Koran, found ripped up in three toilet bowls at a college campus in Texas, with police investigating the incident as a "strange" and "unusual" case due to the school\'s religious and ethnic diversity, while a Muslim student association president has expressed sadness and appreciation for the overwhelming voice of love and support from the community.</s>',
  " Local media in Texas has shared photos of copies of the Islamic holy book, the Koran, found in three toilet bowls at a college campus, leading police to investigate and identify a suspect, while the university's Muslim Student Association and student government have released statements condemning the act as an isolated incident that does not represent the community.</s>",
  ' A mysterious incident occurred at a Texas university when multiple copies of the Islamic holy book, the Koran, were found torn up and placed in three different toilet bowls, prompting an investigation and statements of condemnation from the university community.</s>',
  ' Six copies of the Islamic holy book, the Koran, were found in three toilet bowls at a college campus in Texas, causing an investigation and concern among students and administrators, with police trying to identify a suspect and students expressing their sadness and appreciation for the supportive environment.</s>',
  " Local media photos revealed that the Islamic holy book, the Koran, was ripped up and placed in three toilet bowls at a university in Texas, prompting an investigation by campus police who are trying to identify one of six people seen entering the toilet on the evening of the incident, despite the university's diverse religious and ethnic environment.</s>",
  ' At a university in Texas, six copies of the Islamic holy book, the Koran, were found in three toilet bowls, prompting an investigation and concern among students and administrators, with the police chief describing the incident as "strange" and "very unusual" due to the school\'s religious and ethnic diversity.</s>',
  ' Local media outlets have shared photos of copies of the Islamic holy book, the Koran, found in three different toilet bowls on a college campus, prompting an investigation by campus police who are trying to identify one of six people seen entering the toilet on the night of the incident; the discovery has been described as "strange" and "very unusual" given the religious and ethnic diversity of the school.</s>',
  ' Local media shared photos of the Islamic holy book, the Koran, in three toilet bowls at a university, prompting an investigation and concern from students and officials, with police trying to identify one of six people seen entering the toilet on the evening of the incident and the university community denying that it represents their values.</s>',
  ' Six copies of the Islamic holy book, the Koran, were found ripped up in three toilet bowls at a Texas university, prompting an investigation and concern among students and officials, with the police chief describing it as a "strange" and "very unusual" incident in a diverse campus community.</s>'],
 [' Mo Farah won the 5,000m race at the Diamond League meeting in London with the fastest time in the world this year, clocking 7 minutes and 34.66 seconds, despite allegations of doping against his coach Alberto Salazar, which he denied, and after withdrawing from a previous race due to emotional and physical exhaustion.</s>',
  ' Mo Farah won the 5,000m race at the Diamond League meet in London in a world-leading time of 7 minutes 34.66 seconds, dedicating the victory to his coach Alberto Salazar who has been accused of doping violations, and praising the support he has received from the crowd and fellow athletes.</s>',
  ' Mo Farah won the 5,000m race in London in a world-leading time of 7 minutes and 34.66 seconds, his first victory since allegations of doping against his coach Alberto Salazar surfaced, with the crowd giving him generous applause and Farah celebrating with a smile and his trademark "Mobot" gesture.</s>',
  ' Mo Farah won the 5,000m race at the Glasgow Grand Prix with the fastest time in the world this year, clocking 7:34.66 seconds, after overcoming recent doping allegations against his coach Alberto Salazar and receiving support from the crowd.</s>',
  ' Mo Farah won the 5,000m race at the London Anniversary Games in a world-leading time of 7 minutes and 34.66 seconds, despite facing doping allegations against his coach Alberto Salazar, and dedicated his victory to the support he has received from the crowd.</s>',
  ' Mo Farah won the 5,000m race at the Anniversary Games in London in a time of 7 minutes 34.66 seconds, his fastest time of the year, after overcoming allegations of doping against his coach Alberto Salazar and receiving support from the crowd.</s>',
  ' Mo Farah won the 5,000m race at the Diamond League meeting in London on Thursday, clocking the fastest time in the world this year with a time of 7 minutes 34.66 seconds, despite recent doping allegations against his coach Alberto Salazar and a withdrawal from a previous race due to emotional and physical exhaustion.</s>',
  " Mo Farah won the 5,000m race at the Diamond League meeting in London in a time of 7 minutes 34.66 seconds, dedicating his victory to the support he has received from the crowd and paying tribute to Usain Bolt's celebratory pose.</s>",
  ' Mo Farah won the 5,000m race at the Diamond League meet in London with the fastest time in the world this year, clocking 7 minutes 34.66 seconds, despite recent doping allegations against his coach Alberto Salazar, which he denies, and Farah is not accused of any wrongdoing.</s>',
  ' Mo Farah won the 5,000m race in the Diamond League meet in London with a time of 7 minutes and 34.66 seconds, his fastest time of the year, amidst allegations of doping against his coach Alberto Salazar and amidst his own emotional and physical draining after withdrawing from a previous meet due to the allegations.</s>',
  ' Mo Farah won the 5,000m race at the Diamond League meeting in London in a time of 7 minutes and 34.66 seconds, with the crowd providing generous support despite recent doping allegations against his coach Alberto Salazar, with Farah himself not accused of any wrongdoing.</s>',
  ' Mo Farah won the 5,000m race at the Müller Anniversary Games in London in a world-leading time of 7 minutes 34.66 seconds, with the crowd showing their support despite recent doping allegations against his coach Alberto Salazar.</s>',
  ' Mo Farah won the 5,000m race at the Diamond League meet in London with the fastest time in the world this year, clocking in at 7 minutes 34.66 seconds, despite allegations of doping against his coach Alberto Salazar and having withdrawn from a previous race due to emotional and physical exhaustion.</s>',
  ' Mo Farah won the 5,000m race at the Müller Anniversary Games in London in a time of 7 minutes and 34.66 seconds, clocking the fastest time in the world this year, despite controversy surrounding his coach Alberto Salazar and allegations of doping.</s>',
  ' Mo Farah won the 5,000m race at the Diamond League meeting in London on Tuesday with a time of 7 minutes 34.66 seconds, the fastest time in the world this year, while also receiving generous applause from the crowd despite controversy surrounding his coach Alberto Salazar.</s>'],
 [' Bradford Bulls were liquidated on Tuesday after failing to find a suitable buyer, but the Rugby Football League (RFL) has announced that a new Bradford side will take the place of the old one in the second tier and start the season with a 12-point deduction, with a deadline of January 9 for bids to be submitted and a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new Bradford side will be established and will take the place of the old one in the second tier, starting the season with a 12-point deduction, and setting a deadline of January 9 for bids to be submitted.</s>',
  ' Bradford Bulls were liquidated due to a lack of buyer, but the Rugby Football League (RFL) has established a new side that will take the place of the old one in the second tier with a 12-point deduction, and is accepting bids until January 9th with a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new Bradford side will be established and will take the place of the old one in the second tier, starting the season with a 12-point deduction, and bids to buy the club are being accepted until January 9th with a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new Bradford side will take the place of the old one in the second tier and will start the season with a 12-point deduction, with a deadline of Monday, 9 January for bids to be submitted and a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new Bradford side will take the place of the old one in the second tier with a 12-point deduction, and bids to purchase the club are being accepted until January 9th with a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new side will be established and start the season with a 12-point deduction, with a deadline of January 9 for bids to be submitted and a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated on Tuesday, but the Rugby Football League (RFL) has announced that a new side will be established and will take the place of the old one in the second tier, starting with a 12-point deduction, and bids to purchase the club must be submitted by January 9th with a decision expected within two weeks.</s>',
  ' Bradford Bulls were liquidated due to a lack of buyer, but the Rugby Football League (RFL) plans to reform the club and start it over with a 12-point deduction, giving the new side a chance to succeed despite the challenges ahead.</s>',

In [12]:
joblib.load("/app/cache/topological_entropy_8_09_0.1_graph/Llama-2-7b-chat-hf_ab2aabd38763db812b6a0c964d9918a9_topological_entropy.joblib")

{'topo_entropy': [[0.03864923119544983,
   0.03769388794898987,
   0.03882530331611633,
   0.03864923119544983,
   0.03864923119544983],
  [0.03659293055534363,
   0.03938347101211548,
   0.03686320781707764,
   0.035349905490875244,
   0.037114858627319336],
  [0.03605043888092041,
   0.03622269630432129,
   0.03605043888092041,
   0.03605043888092041,
   0.03605043888092041],
  [0.03479570150375366,
   0.03445911407470703,
   0.031535983085632324,
   0.03366291522979736,
   0.03473302721977234],
  [0.035815924406051636,
   0.035815924406051636,
   0.035815924406051636,
   0.035815924406051636,
   0.035815924406051636],
  [0.04250435531139374,
   0.04250435531139374,
   0.04250435531139374,
   0.04250435531139374,
   0.04250435531139374],
  [0.038470298051834106,
   0.038470298051834106,
   0.03854668140411377,
   0.039040833711624146,
   0.038470298051834106],
  [0.03867298364639282,
   0.03867298364639282,
   0.03867298364639282,
   0.03917732834815979,
   0.03917732834815979],
  [0.03733748197555542,
   0.03479534387588501,
   0.03793337941169739,
   0.03479534387588501,
   0.03478282690048218],
  [0.0389477014541626,
   0.03897401690483093,
   0.03919139504432678,
   0.03802454471588135,
   0.03795263171195984],
  [0.03733855485916138,
   0.03764334321022034,
   0.03733855485916138,
   0.03733855485916138,
   0.03764334321022034],
  [0.03977784514427185,
   0.04125377535820007,
   0.04127049446105957,
   0.04039999842643738,
   0.03876352310180664],
  [0.037142783403396606,
   0.036712586879730225,
   0.03696846961975098,
   0.0347827672958374,
   0.037142783403396606],
  [0.038496583700180054,
   0.038496583700180054,
   0.038496583700180054,
   0.03756490349769592,
   0.03836047649383545],
  [0.036528557538986206,
   0.036528557538986206,
   0.036528557538986206,
   0.036528557538986206,
   0.036528557538986206],
  [0.0359366238117218,
   0.03744027018547058,
   0.036605656147003174,
   0.03725928068161011,
   0.038700997829437256],
  [0.0374068021774292,
   0.03285309672355652,
   0.03285309672355652,
   0.03285309672355652,
   0.03285309672355652],
  [0.038930267095565796,
   0.038930267095565796,
   0.038930267095565796,
   0.038930267095565796,
   0.038930267095565796],
  [0.03725603222846985,
   0.03857883810997009,
   0.03805670142173767,
   0.03738301992416382,
   0.03854727745056152],
  [0.03775978088378906,
   0.03764030337333679,
   0.037422776222229004,
   0.037422776222229004,
   0.036092132329940796],
  [0.03931593894958496,
   0.03931593894958496,
   0.03931593894958496,
   0.03931593894958496,
   0.03931593894958496],
  [0.0426630973815918,
   0.03936430811882019,
   0.03601127862930298,
   0.035808831453323364,
   0.04194536805152893],
  [0.03860437870025635,
   0.03849342465400696,
   0.03865000605583191,
   0.038735926151275635,
   0.038735926151275635],
  [0.03336435556411743,
   0.03332507610321045,
   0.03401336073875427,
   0.033320873975753784,
   0.03345829248428345],
  [0.03849726915359497,
   0.03849726915359497,
   0.03849726915359497,
   0.03849726915359497,
   0.03849726915359497],
  [0.034742265939712524,
   0.034391552209854126,
   0.034391552209854126,
   0.034742265939712524,
   0.03451728820800781],
  [0.038149505853652954,
   0.038149505853652954,
   0.03807830810546875,
   0.038149505853652954,
   0.038149505853652954],
  [0.03734472393989563,
   0.037499427795410156,
   0.037499427795410156,
   0.037499427795410156,
   0.037499427795410156],
  [0.039219409227371216,
   0.039819806814193726,
   0.03983345627784729,
   0.039539635181427,
   0.04106292128562927],
  [0.03761124610900879,
   0.03761124610900879,
   0.03761124610900879,
   0.03761124610900879,
   0.03761124610900879],
  [0.038891613483428955,
   0.038891613483428955,
   0.038866668939590454,
   0.03885987401008606,
   0.038891613483428955],
  [0.04172667860984802,
   0.04172667860984802,
   0.04172667860984802,
   0.04260781407356262,
   0.04172667860984802],
  [0.038274139165878296,
   0.038274139165878296,
   0.040809303522109985,
   0.038274139165878296,
   0.03731897473335266],
  [0.03920692205429077,
   0.03816288709640503,
   0.03811642527580261,
   0.03811642527580261,
   0.03816288709640503],
  [0.04817284643650055,
   0.04059836268424988,
   0.04624892771244049,
   0.04417216777801514,
   0.04719880223274231],
  [0.034036487340927124,
   0.034036487340927124,
   0.037056535482406616,
   0.037032485008239746,
   0.034036487340927124],
  [0.038216471672058105,
   0.03836199641227722,
   0.038129210472106934,
   0.03825792670249939,
   0.038216471672058105],
  [0.03896719217300415,
   0.03588038682937622,
   0.03588038682937622,
   0.03833511471748352,
   0.03839695453643799],
  [0.05106653273105621,
   0.04544056951999664,
   0.047048941254615784,
   0.04578632116317749,
   0.046811237931251526],
  [0.03625001013278961,
   0.04028503596782684,
   0.03619764745235443,
   0.03608733415603638,
   0.03582301735877991],
  [0.03873413801193237,
   0.03906148672103882,
   0.038504451513290405,
   0.038349032402038574,
   0.03906148672103882],
  [0.03395906090736389,
   0.038204848766326904,
   0.034470319747924805,
   0.03417688608169556,
   0.03809550404548645],
  [0.03976526856422424,
   0.03976526856422424,
   0.03976526856422424,
   0.03976526856422424,
   0.03976526856422424],
  [0.041856423020362854,
   0.04144187271595001,
   0.04144187271595001,
   0.04144187271595001,
   0.04144187271595001],
  [0.0427018404006958,
   0.043331146240234375,
   0.0421392023563385,
   0.04304581880569458,
   0.04279142618179321],
  [0.03937062621116638,
   0.03937062621116638,
   0.03932046890258789,
   0.03937062621116638,
   0.03937062621116638],
  [0.037090808153152466,
   0.03714153170585632,
   0.03707277774810791,
   0.03714153170585632,
   0.03714153170585632],
  [0.03801161050796509,
   0.03801161050796509,
   0.038187384605407715,
   0.03796324133872986,
   0.03801161050796509],
  [0.0377616286277771,
   0.03818526864051819,
   0.038174837827682495,
   0.03818526864051819,
   0.03818526864051819],
  [0.04521825909614563,
   0.04468497633934021,
   0.039295494556427,
   0.039295494556427,
   0.03899353742599487],
  [0.04081219434738159,
   0.041602253913879395,
   0.041602253913879395,
   0.04132959246635437,
   0.04132959246635437],
  [0.03988775610923767,
   0.03988775610923767,
   0.03988775610923767,
   0.03988775610923767,
   0.03988775610923767],
  [0.03810536861419678,
   0.03810536861419678,
   0.03810536861419678,
   0.03810536861419678,
   0.03810536861419678],
  [0.04112967848777771,
   0.03969550132751465,
   0.03969550132751465,
   0.03969550132751465,
   0.03969550132751465],
  [0.03923562169075012,
   0.0392109751701355,
   0.03917062282562256,
   0.03913193941116333,
   0.039212942123413086],
  [0.04197147488594055,
   0.04299613833427429,
   0.04299613833427429,
   0.04299613833427429,
   0.04197147488594055],
  [0.03841468691825867,
   0.038358598947525024,
   0.03841468691825867,
   0.03841468691825867,
   0.03841468691825867],
  [0.03740209341049194,
   0.03740209341049194,
   0.03839606046676636,
   0.03740209341049194,
   0.03839606046676636],
  [0.03881850838661194,
   0.039531439542770386,
   0.03957757353782654,
   0.03874218463897705,
   0.03874218463897705],
  [0.044453054666519165,
   0.039862245321273804,
   0.04391896724700928,
   0.04354971647262573,
   0.039862245321273804],
  [0.03389632701873779,
   0.03381979465484619,
   0.03380414843559265,
   0.03441157937049866,
   0.03389632701873779],
  [0.03874775767326355,
   0.03865373134613037,
   0.03874775767326355,
   0.03865373134613037,
   0.03865373134613037],
  [0.03975945711135864,
   0.03975945711135864,
   0.03975945711135864,
   0.03975945711135864,
   0.03975945711135864],
  [0.03739544749259949,
   0.03739544749259949,
   0.03739544749259949,
   0.03739544749259949,
   0.03739544749259949],
  [0.03962621092796326,
   0.03962621092796326,
   0.039546310901641846,
   0.039546310901641846,
   0.03962621092796326],
  [0.03582224249839783,
   0.03594076633453369,
   0.03582224249839783,
   0.03581273555755615,
   0.03563559055328369],
  [0.03698226809501648,
   0.03640410304069519,
   0.03698226809501648,
   0.0364726185798645,
   0.03698226809501648],
  [0.036169201135635376,
   0.03657522797584534,
   0.036398887634277344,
   0.036398887634277344,
   0.03625616431236267],
  [0.040780872106552124,
   0.040780872106552124,
   0.041189610958099365,
   0.04068547487258911,
   0.040586620569229126],
  [0.044813305139541626,
   0.04284176230430603,
   0.04196867346763611,
   0.04149824380874634,
   0.044813305139541626],
  [0.03616151213645935,
   0.03597915172576904,
   0.03652438521385193,
   0.03652438521385193,
   0.03597915172576904],
  [0.03830680251121521,
   0.03830680251121521,
   0.04150804877281189,
   0.04030618071556091,
   0.03991115093231201],
  [0.03830987215042114,
   0.03830987215042114,
   0.03830987215042114,
   0.03830987215042114,
   0.03830987215042114],
  [0.04123184084892273,
   0.04123184084892273,
   0.04123184084892273,
   0.04123184084892273,
   0.04123184084892273],
  [0.039712876081466675,
   0.039494484663009644,
   0.04037037491798401,
   0.039494484663009644,
   0.04154273867607117],
  [0.04284146428108215,
   0.04109635949134827,
   0.04074162244796753,
   0.04062587022781372,
   0.038189709186553955],
  [0.0404319167137146,
   0.0404319167137146,
   0.0404319167137146,
   0.0404319167137146,
   0.0404319167137146],
  [0.037392616271972656,
   0.0389522910118103,
   0.03893032670021057,
   0.03893032670021057,
   0.03849339485168457],
  [0.03989472985267639,
   0.040098875761032104,
   0.040098875761032104,
   0.040098875761032104,
   0.040098875761032104],
  [0.039348483085632324,
   0.039348483085632324,
   0.039348483085632324,
   0.039715975522994995,
   0.040601760149002075],
  [0.03669443726539612,
   0.03675392270088196,
   0.03690922260284424,
   0.037403643131256104,
   0.037403643131256104],
  [0.03918403387069702,
   0.03871750831604004,
   0.03871750831604004,
   0.03871750831604004,
   0.03871750831604004],
  [0.04004618525505066,
   0.039316326379776,
   0.039316326379776,
   0.040181875228881836,
   0.039316326379776],
  [0.04184752702713013,
   0.040073275566101074,
   0.04001644253730774,
   0.035115182399749756,
   0.035115182399749756],
  [0.04002448916435242,
   0.04179888963699341,
   0.04002448916435242,
   0.04002448916435242,
   0.04002448916435242],
  [0.04021811485290527,
   0.04021811485290527,
   0.04005095362663269,
   0.040230900049209595,
   0.04021811485290527],
  [0.039323508739471436,
   0.03949493169784546,
   0.03949493169784546,
   0.039323508739471436,
   0.039323508739471436],
  [0.03686767816543579,
   0.03639993071556091,
   0.03639993071556091,
   0.03686767816543579,
   0.03639993071556091],
  [0.03697061538696289,
   0.03650137782096863,
   0.03702205419540405,
   0.03683081269264221,
   0.03738987445831299],
  [0.03757050633430481,
   0.03757050633430481,
   0.03779339790344238,
   0.03759068250656128,
   0.03759068250656128],
  [0.03680133819580078,
   0.038257896900177,
   0.0372750461101532,
   0.03931751847267151,
   0.03957325220108032],
  [0.04406668245792389,
   0.04178991913795471,
   0.04406668245792389,
   0.04406668245792389,
   0.04406668245792389],
  [0.04025256633758545,
   0.03872498869895935,
   0.04098471999168396,
   0.03721499443054199,
   0.04331082105636597],
  [0.03633546829223633,
   0.038172632455825806,
   0.035464972257614136,
   0.03633546829223633,
   0.035464972257614136],
  [0.038644880056381226,
   0.03855183720588684,
   0.03903511166572571,
   0.038644880056381226,
   0.03806412220001221],
  [0.037175148725509644,
   0.03965359926223755,
   0.03878587484359741,
   0.03713837265968323,
   0.03878587484359741],
  [0.041412174701690674,
   0.04282650351524353,
   0.041412174701690674,
   0.041560351848602295,
   0.03960615396499634],
  [0.03599649667739868,
   0.03599649667739868,
   0.03599649667739868,
   0.03599649667739868,
   0.03599649667739868],
  [0.039703369140625,
   0.04027074575424194,
   0.04027074575424194,
   0.039703369140625,
   0.039703369140625],
  [0.03705674409866333,
   0.03815102577209473,
   0.03843995928764343,
   0.03665938973426819,
   0.03656533360481262],
  [0.03531694412231445,
   0.03754502534866333,
   0.04006737470626831,
   0.03786024451255798,
   0.03639119863510132],
  [0.04010888934135437,
   0.038557618856430054,
   0.038557618856430054,
   0.03996238112449646,
   0.038557618856430054],
  [0.038993269205093384,
   0.038961201906204224,
   0.038488924503326416,
   0.037895381450653076,
   0.038488924503326416],
  [0.03829649090766907,
   0.03670156002044678,
   0.03864249587059021,
   0.038278937339782715,
   0.03810736536979675],
  [0.03632953763008118,
   0.03639036417007446,
   0.03619647026062012,
   0.036492228507995605,
   0.03641662001609802],
  [0.038020551204681396,
   0.038020551204681396,
   0.03970170021057129,
   0.038020551204681396,
   0.038020551204681396],
  [0.03940114378929138,
   0.03940114378929138,
   0.03940114378929138,
   0.03940114378929138,
   0.03940114378929138],
  [0.03863516449928284,
   0.04102155566215515,
   0.038254350423812866,
   0.038254350423812866,
   0.04046514630317688],
  [0.03539028763771057,
   0.03681051731109619,
   0.035218238830566406,
   0.035498350858688354,
   0.03514617681503296],
  [0.03662958741188049,
   0.038322269916534424,
   0.03999829292297363,
   0.04026949405670166,
   0.037956565618515015],
  [0.037059932947158813,
   0.0383610725402832,
   0.037059932947158813,
   0.0383610725402832,
   0.0383610725402832],
  [0.040218502283096313,
   0.03907087445259094,
   0.03974631428718567,
   0.03974631428718567,
   0.040222227573394775],
  [0.03671109676361084,
   0.03671902418136597,
   0.03671902418136597,
   0.03671109676361084,
   0.036686867475509644],
  [0.03753778338432312,
   0.03753778338432312,
   0.03753778338432312,
   0.03753778338432312,
   0.03753778338432312],
  [0.03787791728973389,
   0.03525298833847046,
   0.03696092963218689,
   0.03775373101234436,
   0.036069899797439575],
  [0.04270601272583008,
   0.04090380668640137,
   0.040632039308547974,
   0.04475897550582886,
   0.04254418611526489],
  [0.038781702518463135,
   0.038781702518463135,
   0.03877103328704834,
   0.03842288255691528,
   0.038487762212753296],
  [0.03951340913772583,
   0.03951340913772583,
   0.03951340913772583,
   0.03951340913772583,
   0.03855237364768982],
  [0.03502380847930908,
   0.03498345613479614,
   0.035135239362716675,
   0.033669739961624146,
   0.03293311595916748],
  [0.037510961294174194,
   0.03729650378227234,
   0.037510961294174194,
   0.03729650378227234,
   0.03767460584640503],
  [0.04027128219604492,
   0.04027128219604492,
   0.04027128219604492,
   0.04027128219604492,
   0.03972241282463074],
  [0.03553187847137451,
   0.03876051306724548,
   0.038947880268096924,
   0.03975147008895874,
   0.03557828068733215],
  [0.038081198930740356,
   0.037742555141448975,
   0.037108927965164185,
   0.037351131439208984,
   0.03706318140029907],
  [0.03875240683555603,
   0.03785046935081482,
   0.0379558801651001,
   0.03851896524429321,
   0.0379558801651001],
  [0.03676152229309082,
   0.03682878613471985,
   0.03775140643119812,
   0.03649529814720154,
   0.03676152229309082],
  [0.03688672184944153,
   0.038025856018066406,
   0.03688672184944153,
   0.03804826736450195,
   0.037648797035217285],
  [0.038732945919036865,
   0.038732945919036865,
   0.03870609402656555,
   0.03870609402656555,
   0.038732945919036865],
  [0.038925617933273315,
   0.038925617933273315,
   0.03881540894508362,
   0.038925617933273315,
   0.03881540894508362],
  [0.04014402627944946,
   0.04014402627944946,
   0.04014402627944946,
   0.04014402627944946,
   0.04014402627944946],
  [0.03676268458366394,
   0.036940157413482666,
   0.03676268458366394,
   0.036940157413482666,
   0.03676268458366394],
  [0.0374140739440918,
   0.03800287842750549,
   0.03730103373527527,
   0.03749161958694458,
   0.03753119707107544],
  [0.03171241283416748,
   0.03171241283416748,
   0.03171241283416748,
   0.03171241283416748,
   0.03171241283416748],
  [0.037665486335754395,
   0.03765183687210083,
   0.037665486335754395,
   0.037580013275146484,
   0.03779292106628418],
  [0.03711491823196411,
   0.0400976836681366,
   0.040178507566452026,
   0.03711491823196411,
   0.03711491823196411],
  [0.03718563914299011,
   0.03749224543571472,
   0.03718563914299011,
   0.03718563914299011,
   0.03718563914299011],
  [0.040079265832901,
   0.039815038442611694,
   0.039815038442611694,
   0.040079265832901,
   0.039815038442611694],
  [0.03952521085739136,
   0.0403001606464386,
   0.0388931930065155,
   0.0388931930065155,
   0.0388931930065155],
  [0.03980672359466553,
   0.03980672359466553,
   0.03980672359466553,
   0.03980672359466553,
   0.0396856963634491],
  [0.037229716777801514,
   0.037229716777801514,
   0.037229716777801514,
   0.03738334774971008,
   0.03738334774971008],
  [0.03739234805107117,
   0.03739234805107117,
   0.03864607214927673,
   0.0379638671875,
   0.03844514489173889],
  [0.037237465381622314,
   0.037237465381622314,
   0.037237465381622314,
   0.037237465381622314,
   0.037237465381622314],
  [0.03720730543136597,
   0.03720730543136597,
   0.03720730543136597,
   0.03720730543136597,
   0.03720730543136597],
  [0.03617227077484131,
   0.0364057719707489,
   0.03638488054275513,
   0.03621715307235718,
   0.036340951919555664],
  [0.038287848234176636,
   0.038287848234176636,
   0.038287848234176636,
   0.038579732179641724,
   0.038579732179641724],
  [0.03135308623313904,
   0.032891303300857544,
   0.03094884753227234,
   0.03217098116874695,
   0.03163212537765503],
  [0.03952741622924805,
   0.0395074188709259,
   0.0395074188709259,
   0.03939622640609741,
   0.0395074188709259],
  [0.0367642343044281,
   0.03908216953277588,
   0.0367642343044281,
   0.038615792989730835,
   0.0367642343044281],
  [0.0394226610660553,
   0.039617836475372314,
   0.040645986795425415,
   0.038416892290115356,
   0.03966999053955078],
  [0.03911721706390381,
   0.03911721706390381,
   0.03941702842712402,
   0.038807064294815063,
   0.03941702842712402],
  [0.040158092975616455,
   0.041532307863235474,
   0.04013168811798096,
   0.04013168811798096,
   0.041532307863235474],
  [0.03986135125160217,
   0.03986135125160217,
   0.03986135125160217,
   0.03986135125160217,
   0.03986135125160217],
  [0.03858131170272827,
   0.03748580813407898,
   0.0370868444442749,
   0.03748580813407898,
   0.03798097372055054],
  [0.031760185956954956,
   0.03165587782859802,
   0.03167662024497986,
   0.03165587782859802,
   0.03165587782859802],
  [0.038081586360931396,
   0.038081586360931396,
   0.03817489743232727,
   0.038081586360931396,
   0.038081586360931396],
  [0.03992512822151184,
   0.03992512822151184,
   0.03992512822151184,
   0.03992512822151184,
   0.04280838370323181],
  [0.045498549938201904,
   0.04654449224472046,
   0.041026949882507324,
   0.04535427689552307,
   0.04438689351081848],
  [0.03816962242126465,
   0.039653778076171875,
   0.04071798920631409,
   0.03909003734588623,
   0.03909003734588623],
  [0.03652578592300415,
   0.03683236241340637,
   0.036719948053359985,
   0.037136226892471313,
   0.03530305624008179],
  [0.03735494613647461,
   0.03735494613647461,
   0.03735494613647461,
   0.038030266761779785,
   0.03735494613647461],
  [0.038539111614227295,
   0.0377449095249176,
   0.038245826959609985,
   0.037777841091156006,
   0.03825950622558594],
  [0.03914937376976013,
   0.039142489433288574,
   0.039010077714920044,
   0.039142489433288574,
   0.03914937376976013],
  [0.03935709595680237,
   0.04060134291648865,
   0.03948691487312317,
   0.03935709595680237,
   0.039986222982406616],
  [0.04534882307052612,
   0.03926199674606323,
   0.04017952084541321,
   0.03926199674606323,
   0.03927510976791382],
  [0.03508421778678894,
   0.03447383642196655,
   0.035370320081710815,
   0.03502511978149414,

In [17]:
X["label"] = y

In [27]:
X["sent_scores"] = joblib.load("cache/sent_scores_8_09/Llama-2-7b-chat-hf_ab2aabd38763db812b6a0c964d9918a9_sent_scores.joblib")

In [21]:
for i in range(100, 110):
    print(X.iloc[i]["prompt"])
    print(X.iloc[i]["response"])
    print(X.iloc[i]["gen_responses"])
    print(X.iloc[i]["topo_entropy"])
    print(X.iloc[i]["label"])

<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: The principles of imperialism are often generalizable to the policies and practices of the British Empire "during the last generation, and proceeds rather by diagnosis than by historical description". British imperialism often used the concept of Terra nullius (Latin expression which stems from Roman law meaning 'empty land'). The country of Australia serves as a case study in relation to British settlement and colonial rule of the continent in the eighteenth century, as it was premised on terra nullius, and its settlers considered it unused by its sparse Aboriginal inhabitants.
Question: What law justified British imperialism?
Answer:  [/INST]
 The law that justified British imperialism during the last generation was the concept of Terra nullius, which was used to justify the occupation and colonization of lands deemed unused or unoccupied by indigenous peoples.
[" The law that justified British imperialism was the concept of Terra nullius, a Latin expression stemming from Roman law meaning 'empty land.'</s>", ' The law that justified British imperialism in Australia during the 18th century was the concept of Terra nullius, which was based on the idea that the land was unused by its sparse Aboriginal inhabitants.</s>', " The law that justified British imperialism in the context of the settlement and colonial rule of Australia in the eighteenth century was the concept of Terra nullius, which was a Latin expression meaning 'empty land' and was used to justify the idea that Australia was unused by its sparse Aboriginal inhabitants.</s>", ' The law that justified British imperialism in the context provided is Terra nullius, which was used to justify the premise that Australia was unused and unoccupied by its Aboriginal inhabitants.</s>', " According to the given context, the law that justified British imperialism was the concept of Terra nullius, which was a Latin expression stemming from Roman law meaning 'empty land'.</s>", " The law that justified British imperialism during the last generation was Terra nullius, a Latin expression that stems from Roman law meaning 'empty land.'</s>", ' The law that justified British imperialism in Australia during the 18th century was the concept of Terra nullius, which was based on the idea that the land was unused by its sparse Aboriginal inhabitants.</s>', ' The law that justified British imperialism was the concept of Terra nullius, which was used to justify the occupation and colonization of lands that were considered unused or unclaimed by their indigenous inhabitants.</s>', ' The law that justified British imperialism in Australia during the 18th century was the concept of Terra nullius, which was based on the idea that the land was unused by its sparse Aboriginal inhabitants.</s>', ' The law that justified British imperialism during the last generation was the concept of Terra nullius, which was used to justify the settlement and colonial rule of the continent of Australia in the eighteenth century.</s>', ' The law that justified British imperialism in the context of the case study of Australia is the concept of Terra nullius, which was used to justify the premise that the continent was unused by its sparse Aboriginal inhabitants.</s>', " The law that justified British imperialism during the last generation was the concept of Terra nullius, a Latin expression stemming from Roman law meaning 'empty land.'</s>", ' The law that justified British imperialism in relation to the concept of terra nullius was the principle of "empty land," which was based on Roman law and was used to justify the British settlement and colonial rule of the continent in Australia in the eighteenth century.</s>', ' The law that justified British imperialism in Australia was the concept of Terra nullius, which was based on the idea that the land was unused by its sparse Aboriginal inhabitants.</s>', ' The law that justified British imperialism in Australia was the concept of Terra nullius, which was used to justify the premise that the land was unused by its sparse Aboriginal inhabitants.</s>']
[0.03531694412231445, 0.03754502534866333, 0.04006737470626831, 0.03786024451255798, 0.03639119863510132]
0
<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: Stage 3 is the final stage of the bill and is considered at a meeting of the whole Parliament. This stage comprises two parts: consideration of amendments to the bill as a general debate, and a final vote on the bill. Opposition members can table "wrecking amendments" to the bill, designed to thwart further progress and take up parliamentary time, to cause the bill to fall without a final vote being taken. After a general debate on the final form of the bill, members proceed to vote at Decision Time on whether they agree to the general principles of the final bill.
Question: When do members proceed to vote on whether they agree to the principles of the final bill?
Answer:  [/INST]
 Members proceed to vote on whether they agree to the general principles of the final bill after a general debate on the final form of the bill at Decision Time.
[' Members proceed to vote on whether they agree to the principles of the final bill after a general debate on the final form of the bill during Decision Time.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill at Decision Time.</s>', ' After a general debate on the final form of the bill, members proceed to vote at Decision Time on whether they agree to the general principles of the final bill.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the general principles of the final bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the general principles of the final bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill after a general debate on the final form of the bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the general principles of the final bill after a general debate on the final form of the bill at Decision Time.</s>', ' After a general debate on the final form of the bill, members proceed to vote at Decision Time on whether they agree to the general principles of the final bill.</s>', ' After a general debate on the final form of the bill, members proceed to vote at Decision Time on whether they agree to the general principles of the final bill.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill after a general debate on the final form of the bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the general principles of the final bill after a general debate on the final form of the bill at Decision Time.</s>', ' Members proceed to vote on whether they agree to the principles of the final bill after a general debate on the final form of the bill during Decision Time.</s>']
[0.04010888934135437, 0.038557618856430054, 0.038557618856430054, 0.03996238112449646, 0.038557618856430054]
0
<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: ARPANET and SITA HLN became operational in 1969. Before the introduction of X.25 in 1973, about twenty different network technologies had been developed. Two fundamental differences involved the division of functions and tasks between the hosts at the edge of the network and the network core. In the datagram system, the hosts have the responsibility to ensure orderly delivery of packets. The User Datagram Protocol (UDP) is an example of a datagram protocol. In the virtual call system, the network guarantees sequenced delivery of data to the host. This results in a simpler host interface with less functionality than in the datagram model. The X.25 protocol suite uses this network type.
Question: WHat does UserDatagram Protocol gaurentee
Answer:  [/INST]
 The UserDatagram Protocol (UDP) guarantees ordered delivery of packets.
[' UserDatagram Protocol (UDP) guarantees sequenced delivery of packets to the host.</s>', ' The User Datagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees ordered delivery of packets.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>', ' The UserDatagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>', ' UserDatagram Protocol guarantees sequenced delivery of data to the host.</s>', ' The User Datagram Protocol (UDP) guarantees sequenced delivery of data to the host.</s>']
[0.038993269205093384, 0.038961201906204224, 0.038488924503326416, 0.037895381450653076, 0.038488924503326416]
1
<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: On October 6, 1973, Syria and Egypt, with support from other Arab nations, launched a surprise attack on Israel, on Yom Kippur. This renewal of hostilities in the Arab–Israeli conflict released the underlying economic pressure on oil prices. At the time, Iran was the world's second-largest oil exporter and a close US ally. Weeks later, the Shah of Iran said in an interview: "Of course [the price of oil] is going to rise... Certainly! And how!... You've [Western nations] increased the price of the wheat you sell us by 300 percent, and the same for sugar and cement... You buy our crude oil and sell it back to us, refined as petrochemicals, at a hundred times the price you've paid us... It's only fair that, from now on, you should pay more for oil. Let's say ten times more."
Question: Why did the Shah of Iran gave an interview?
Answer:  [/INST]
 The Shah of Iran gave an interview to express his opinions on the recent increase in oil prices and to criticize the practices of Western nations, particularly the United States, in the oil market.
[' The Shah of Iran gave an interview to express his frustration and outrage at the exploitative prices being charged by Western nations for Iranian oil, and to call for fairer pricing in the oil trade.</s>', " The Shah of Iran gave an interview to express his views on the recent increase in oil prices and to criticize Western nations for exploiting Iran's resources.</s>", ' The Shah of Iran gave an interview to address his concerns about the exploitative economic practices of Western nations, particularly the US, in the context of the Arab-Israeli conflict and the impact on oil prices.</s>', ' The Shah of Iran gave an interview to express his views on the recent increase in oil prices, specifically mentioning the perceived unfairness of Western nations selling oil to Iran at a low price and then turning around and selling refined petrochemicals to Iran at a much higher price.</s>', " The Shah of Iran gave an interview to express his country's opposition to the recent increase in oil prices by Western nations, and to demand fairer treatment in their economic dealings with Iran.</s>", ' The Shah of Iran gave an interview to address the issue of oil prices and the perceived unfairness of the global oil trade, particularly the high prices Western nations were charging for Iranian crude oil while simultaneously selling refined petrochemicals back to Iran at a much higher price.</s>', ' The Shah of Iran gave an interview to express his frustration and indignation at the perceived unfairness of the global oil market, specifically the high prices Western nations were charging for oil and other essential goods while selling them back to Iran at greatly inflated prices.</s>', ' The Shah of Iran gave an interview to address the issue of oil prices and the economic pressure it had placed on Arab nations, including Iran, as a result of the surprise attack on Israel during the Yom Kippur War.</s>', ' The Shah of Iran gave an interview to express his grievances against Western nations, particularly the United States, regarding the high prices they had charged for essential goods such as wheat, sugar, and cement, while also accusing them of profiting from the sale of crude oil at inflated prices.</s>', ' The Shah of Iran gave an interview to express his views on the recent increase in oil prices and to challenge the economic policies of Western nations towards Iran.</s>', " The Shah of Iran gave an interview to address the economic pressure on oil prices due to the surprise attack on Israel on Yom Kippur, and to express Iran's dissatisfaction with the unfair prices being charged by Western nations for oil and other goods.</s>", ' The Shah of Iran gave an interview to express his views on the recent increase in oil prices, which he believed was unfairly high and wanted to bring attention to the issue.</s>', " The Shah of Iran gave an interview to address the issue of the increasing price of oil and the economic pressure it had put on Arab nations, including Iran, and to express his country's desire for fairness in the global oil market.</s>", ' The Shah of Iran gave an interview to express his views on the recent increase in oil prices, which he believed was unfair and wanted to bring attention to the issue.</s>', " The Shah of Iran gave an interview to address the issue of unfair pricing of oil and other goods by Western nations, particularly the United States, and to demand a higher price for Iran's crude oil.</s>"]
[0.03829649090766907, 0.03670156002044678, 0.03864249587059021, 0.038278937339782715, 0.03810736536979675]
0
<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: Most species are hermaphrodites—a single animal can produce both eggs and sperm, meaning it can fertilize its own egg, not needing a mate. Some are simultaneous hermaphrodites, which can produce both eggs and sperm at the same time. Others are sequential hermaphrodites, in which the eggs and sperm mature at different times. Fertilization is generally external, although platyctenids' eggs are fertilized inside their parents' bodies and kept there until they hatch. The young are generally planktonic and in most species look like miniature cydippids, gradually changing into their adult shapes as they grow. The exceptions are the beroids, whose young are miniature beroids with large mouths and no tentacles, and the platyctenids, whose young live as cydippid-like plankton until they reach near-adult size, but then sink to the bottom and rapidly metamorphose into the adult form. In at least some species, juveniles are capable of reproduction before reaching the adult size and shape. The combination of hermaphroditism and early reproduction enables small populations to grow at an explosive rate.
Question: Which group keep the eggs are fertilized and kept inside the parent's body until they hatch?
Answer:  [/INST]
 The platyctenids are the group that keeps the eggs fertilized and inside the parent's body until they hatch.
[" The platyctenids keep their eggs fertilized and inside their parents' bodies until they hatch.</s>", " The platyctenids keep their eggs inside their parents' bodies until they hatch.</s>", ' Platyctenids.</s>', " The platyctenids keep their eggs fertilized and inside their parent's bodies until they hatch.</s>", " The platyctenids keep the eggs fertilized and inside their parents' bodies until they hatch.</s>", " The group that keeps the eggs fertilized and inside the parent's body until they hatch are the platyctenids.</s>", " The platyctenids are the group that keep the eggs fertilized and inside their parent's body until they hatch.</s>", " The group that keeps the eggs fertilized and inside their parent's body until they hatch are the platyctenids.</s>", " The platyctenids are the group that keep the eggs fertilized and kept inside the parent's body until they hatch.</s>", " The group that keeps the eggs fertilized and inside the parent's body until they hatch are the platyctenids.</s>", " The group that keeps the eggs fertilized and inside their parent's body until they hatch are the platyctenids.</s>", " The group that keeps the eggs fertilized and inside the parent's body until they hatch are the platyctenids.</s>", " The group of animals that keep the eggs fertilized and kept inside their parents' bodies until they hatch are the platyctenids.</s>", " The platyctenids are the group that keeps the eggs fertilized and inside the parent's body until they hatch.</s>", " The group that keeps the eggs fertilized and inside the parent's body until they hatch are the platyctenids.</s>"]
[0.03632953763008118, 0.03639036417007446, 0.03619647026062012, 0.036492228507995605, 0.03641662001609802]
0
<s> [INST] Given the context, answer the question in a single brief but complete sentence. Note that your answer should be strictly based on the given context. In case the context does not contain the necessary information to answer the question, please reply with: "Unable to answer based on given context."
Context: In economics, notable Nobel Memorial Prize in Economic Sciences winners Milton Friedman, a major advisor to Republican U.S. President Ronald Reagan and Conservative British Prime Minister Margaret Thatcher, George Stigler, Nobel laureate and proponent of regulatory capture theory, Gary Becker, an important contributor to the family economics branch of economics, Herbert A. Simon, responsible for the modern interpretation of the concept of organizational decision-making, Paul Samuelson, the first American to win the Nobel Memorial Prize in Economic Sciences, and Eugene Fama, known for his work on portfolio theory, asset pricing and stock market behaviour, are all graduates. American economist, social theorist, political philosopher, and author Thomas Sowell is also an alumnus.

In [28]:
X

,id,prompt,response,name,gen_responses,topo_entropy,label,sent_scores
0,5725d662ec44d21400f3d68b,"<s> [INST] Given the context, answer the quest...",Kearney Park hosts the largest Civil War reen...,squad,[ Kearney Park hosts the largest Civil War ree...,"[0.03864923119544983, 0.03769388794898987, 0.0...",0,[0.5023544224648504]
1,57280f974b864d1900164372,"<s> [INST] Given the context, answer the quest...",Civil disobedience is typically defined as th...,squad,[ Civil disobedience is typically defined as a...,"[0.03659293055534363, 0.03938347101211548, 0.0...",1,[0.024486982123926283]
2,5725f5b1271a42140099d374,"<s> [INST] Given the context, answer the quest...",Most of the wind in Fresno originates from th...,squad,[ Most of the wind in Fresno originates from t...,"[0.03605043888092041, 0.03622269630432129, 0.0...",0,[0.04086440542984444]
3,572751b4708984140094dc1b,"<s> [INST] Given the context, answer the quest...",A complex net of contracts and other legal ob...,squad,[ A complex net of contracts and other legal o...,"[0.03479570150375366, 0.03445911407470703, 0.0...",0,[0.29504092267404]
4,5726400589a1e219009ac5ef,"<s> [INST] Given the context, answer the quest...",The small tentacles on Cydippids are called t...,squad,[ The small tentacles on Cydippids are called ...,"[0.035815924406051636, 0.035815924406051636, 0...",0,[0.0013651994134609897]
...,...,...,...,...,...,...,...,...
795,573010fab2c2fd14005687da,"<s> [INST] Given the context, answer the quest...",Algeria,squad,"[ Algeria</s>, Algeria.</s>, Algeria.</s>, ...","[0.03765600919723511, 0.03777095675468445, 0.0...",0,[0.010986236855387688]
796,572ffee1947a6a140053cf15,"<s> [INST] Given the context, answer the quest...",The All India Muslim League.,squad,"[ Based on the given context, Iqbal joined the...","[0.039147913455963135, 0.0382821261882782, 0.0...",0,[0.0072065873071551325]
797,57282358ff5b5019007d9dde,"<s> [INST] Given the context, answer the quest...","According to the given context, Jacksonville'...",squad,"[ According to the given context, Jacksonville...","[0.039566993713378906, 0.04000416398048401, 0....",0,[0.004585791767264406]
798,5725c071271a42140099d12b,"<s> [INST] Given the context, answer the quest...",It joined the easterly flow toward the Atlantic.,squad,[ It joined the easterly flow toward the Atlan...,"[0.040326327085494995, 0.040326327085494995, 0...",0,[0.0014943561051040887]
799,572ffc99947a6a140053cefa,"<s> [INST] Given the context, answer the quest...",Sadat was rewarded by the Islamists for his a...,squad,[ Sadat was rewarded by the Islamists with pol...,"[0.036675214767456055, 0.037118107080459595, 0...",1,[0.8326394758497675]

In [35]:
from pprint import pprint

pprint(X.iloc[-1]["prompt"])

('<s> [INST] Given the context, answer the question in a single brief but '
 'complete sentence. Note that your answer should be strictly based on the '
 'given context. In case the context does not contain the necessary '
 'information to answer the question, please reply with: "Unable to answer '
 'based on given context."\n'
 'Context: Egyptian President Anwar Sadat – whose policies included opening '
 "Egypt to Western investment (infitah); transferring Egypt's allegiance from "
 'the Soviet Union to the United States; and making peace with Israel – '
 'released Islamists from prison and welcomed home exiles in tacit exchange '
 'for political support in his struggle against leftists. His "encouraging of '
 'the emergence of the Islamist movement" was said to have been "imitated by '
 'many other Muslim leaders in the years that followed."  This "gentlemen\'s '
 'agreement" between Sadat and Islamists broke down in 1975 but not before '
 'Islamists came to completely dominate university student unions. Sadat was '
 'later assassinated and a formidable insurgency was formed in Egypt in the '
 '1990s. The French government has also been reported to have promoted '
 'Islamist preachers "in the hope of channeling Muslim energies into zones of '
 'piety and charity."\n'
 'Question: How was Sadat rewarded by the Islamists for his attempts to bring '
 'Egypt into modern times and civilization?\n'
 'Answer:  [/INST]')

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv("/app/data/fixed/SQuAD/squad_Llama-2-7b-chat-hf.csv")

In [43]:
df.iloc[799]["answers"]

"['Islamists came to completely dominate university student unions', 'assassinated']"

In [44]:
X

,id,prompt,response,name,gen_responses,topo_entropy,label,sent_scores
0,5725d662ec44d21400f3d68b,"<s> [INST] Given the context, answer the quest...",Kearney Park hosts the largest Civil War reen...,squad,[ Kearney Park hosts the largest Civil War ree...,"[0.03864923119544983, 0.03769388794898987, 0.0...",0,[0.5023544224648504]
1,57280f974b864d1900164372,"<s> [INST] Given the context, answer the quest...",Civil disobedience is typically defined as th...,squad,[ Civil disobedience is typically defined as a...,"[0.03659293055534363, 0.03938347101211548, 0.0...",1,[0.024486982123926283]
2,5725f5b1271a42140099d374,"<s> [INST] Given the context, answer the quest...",Most of the wind in Fresno originates from th...,squad,[ Most of the wind in Fresno originates from t...,"[0.03605043888092041, 0.03622269630432129, 0.0...",0,[0.04086440542984444]
3,572751b4708984140094dc1b,"<s> [INST] Given the context, answer the quest...",A complex net of contracts and other legal ob...,squad,[ A complex net of contracts and other legal o...,"[0.03479570150375366, 0.03445911407470703, 0.0...",0,[0.29504092267404]
4,5726400589a1e219009ac5ef,"<s> [INST] Given the context, answer the quest...",The small tentacles on Cydippids are called t...,squad,[ The small tentacles on Cydippids are called ...,"[0.035815924406051636, 0.035815924406051636, 0...",0,[0.0013651994134609897]
...,...,...,...,...,...,...,...,...
795,573010fab2c2fd14005687da,"<s> [INST] Given the context, answer the quest...",Algeria,squad,"[ Algeria</s>, Algeria.</s>, Algeria.</s>, ...","[0.03765600919723511, 0.03777095675468445, 0.0...",0,[0.010986236855387688]
796,572ffee1947a6a140053cf15,"<s> [INST] Given the context, answer the quest...",The All India Muslim League.,squad,"[ Based on the given context, Iqbal joined the...","[0.039147913455963135, 0.0382821261882782, 0.0...",0,[0.0072065873071551325]
797,57282358ff5b5019007d9dde,"<s> [INST] Given the context, answer the quest...","According to the given context, Jacksonville'...",squad,"[ According to the given context, Jacksonville...","[0.039566993713378906, 0.04000416398048401, 0....",0,[0.004585791767264406]
798,5725c071271a42140099d12b,"<s> [INST] Given the context, answer the quest...",It joined the easterly flow toward the Atlantic.,squad,[ It joined the easterly flow toward the Atlan...,"[0.040326327085494995, 0.040326327085494995, 0...",0,[0.0014943561051040887]
799,572ffc99947a6a140053cefa,"<s> [INST] Given the context, answer the quest...",Sadat was rewarded by the Islamists for his a...,squad,[ Sadat was rewarded by the Islamists with pol...,"[0.036675214767456055, 0.037118107080459595, 0...",1,[0.8326394758497675]

In [45]:
import numpy as np 
mean_topo_entropy = X["topo_entropy"].apply(np.mean, axis=0)

In [46]:
mean_topo_entropy

0      0.038493
1      0.037061
2      0.036085
3      0.033837
4      0.035816
         ...
795    0.037725
796    0.038455
797    0.039870
798    0.041494
799    0.036667
Name: topo_entropy, Length: 800, dtype: float64

In [47]:
from scipy import stats

In [50]:
sem_ent = X["sent_scores"].apply(lambda x: x[0])

In [51]:
stats.pearsonr(mean_topo_entropy, sem_ent)

PearsonRResult(statistic=-0.11077619639443256, pvalue=0.0017011222324564603)